### ISSUE TITLE
Re-enable and fix skipped Dial tests

### ISSUE THREAD

**Issue by jackwotherspoon** [GoogleCloudPlatform/cloud-sql-proxy#1228]
As part of moving testing builds over to Github Actions #1222 a couple tests became flaky. They are currently being skipped to unblock builds, this issue is to re-enable the tests and fix the cause of them being flaky.

Flaky tests being skipped:

- [ ] [SingleInstanceDial](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/main/tests/healthcheck_test.go#L33)
- [ ] [MultiInstanceDial](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/main/tests/alldb_test.go#L42)

**Comment by enocom** [comment]
Closing this as stale. We've since ported these tests to v2 which is what we recommend people use today.
