### ISSUE TITLE
Add support for debug logging

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/cloud-sql-proxy#1255]
Sometimes it helps to know more than what the proxy logs (certificate expiration times, for example). This is a feature request to add support for debug logging, as enabled by a `--debug` flag or similar. When callers supplied this flag, the proxy would be much more chatty about its internal state, the certificates, the connection data, etc.

**Comment by trajan0x** [comment]
I'd also like to see a way to change log level down (e..g ignore accepted/closed levels)

**Comment by enocom** [comment]
@trajan0x Have you checked out the v2 proxy? It's much more terse about what it logs. I'd be interested if you'd want to adjust still further.

**Comment by trajan0x** [comment]
@enocom here's what that looks like on my end:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/83933037/193883476-490563e3-2613-4713-a28b-906a7321c77d.png">


This is about .2 seconds from a single pod

**Comment by enocom** [comment]
That's pretty chatty. Seems like a `--quiet` flag that just logged errors would be in order.

**Comment by enocom** [comment]
See https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1452.

**Comment by enocom** [comment]
We will wait until slog lands in the standard library and then add this.

https://github.com/golang/go/issues/56345

**Comment by enocom** [comment]
Going to close this for now.
