### ISSUE TITLE
Can we use Cloud SQL proxy when we don't the know DB we are connecting to until runtime

### ISSUE THREAD

**Issue by harkinj** [GoogleCloudPlatform/cloud-sql-proxy#1342]
## Question
Hi,
We plan to connect to a different Cloud SQL Postgres DB  at runtime based on some runtime info.
So we won't know the connection info to the relevant DB at deployment time rather we have it at runtime.
Our app is running in GKE.
Is it still possible to use Cloud sql proxy or should we use something like :
https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine#private-ip
Thanks for all info.
John
## Additional Context
Please reference any other relevant issues, PRs, descriptions, or screenshots here.

**Comment by enocom** [comment]
Using the proxy with FUSE enabled will do what you're looking for. Basically, you start the proxy like so:

``` shell
cloud_sql_proxy --fuse -dir /cloudsql # or whatever directory you like
```

And then when you application resolves an instance connection name at runtime, it can then connect to `/cloudsql/<INSTANCE_CONNECTION_NAME`. The proxy sees that path and does all the necessary connection initialization.

I personally haven't tried FUSE on GKE, but it should work. Take a look at [a previous issue comment](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/444#issuecomment-725570671) where someone posted an example of how to do this.

If you have any trouble setting this up, feel free to report back and I'll see what I can do to make this easier.

**Comment by harkinj** [comment]
Hi,
Thanks for the information.
we will give it a go over the next week or so and hope all goes well.
Regards
John

**Comment by enocom** [comment]
I'm going to close this out. Feel free to re-open if you would like to discuss further.
