### ISSUE TITLE
[v2] prometheus and health checks listen on localhost instead of anyhost

### ISSUE THREAD

**Issue by daquinoaldo** [GoogleCloudPlatform/cloud-sql-proxy#1359]
## Bug Description

When started with `"--prometheus` and `--health-check`, the HTTP server listens for requests on localhost, but it should listen on anyhost. Otherwise, it cannon be accessed using the Pod IP (from Prometheus, kubelet, and Istio).

## How to reproduce

  1. Run the Pod with `--health-check`
  2. Create an ephemeral container with `debug` and run `curl localhost:9090/readiness` and `curl <pod IP>:9090/readiness`. The latter won't work.

## Environment

- GKE 1.23 with COS containerd nodes
- Cloud SQL Proxy version: docker container built from the v2.0.0.preview.0 tag, targeting Linux amd64

EDIT: I can open a pull request if you want. I tested it, and it worked by replacing `localhost` with `0.0.0.0` in the HTTP server.

**Comment by enocom** [comment]
Thanks for the bug report. I think defaulting to localhost but letting people change the host with a flag is the way to go here. What do you think @daquinoaldo?

**Comment by enocom** [comment]
I’m thinking mostly about supporting this feature on GCE where any host could be a security problem.

**Comment by daquinoaldo** [comment]
Sorry for the late reply. Sure, a flag does the job!
I added a couple of comments in the PR. Thank you for taking care of it!
