### ISSUE TITLE
Intermittent timeout on connects

### ISSUE THREAD

**Issue by carlpett** [GoogleCloudPlatform/cloud-sql-proxy#1371]
## Bug Description

A couple of times per day, we get a odd timeout error logged in CloudSQL when connecting to instances, and a "authentication failed" error message on the client:

```
2022-09-02 14:08:13.336 UTC [488068]: [2-1] db=[dbname],user=[serviceaccount-id]@[project].iam DETAIL:  Deadline Exceeded
Connection matched pg_hba.conf line 21: "local   all           +cloudsqliamserviceaccount         cloudsql-iam-svc-acct"
```
```
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  Cloud SQL IAM service account authentication failed for user [serviceaccount-id]@[project].iam
```

## How to reproduce

Very unclear. Our application currently uses a crash+restart as a retry mechanism, and connecting works when coming back. Existing open connections appear to work while the new one fails. There is no clear indication in metrics that there is a load related issue.

We're seeing this across several applications, different service accounts and cloud sql instances, however, so it doesn't appear to be related to a single "bad" thing.

## Environment

1. OS type and version: GKE COS v1.21.13-gke.900
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): 1.30.1

**Comment by enocom** [comment]
@carlpett are these timeouts all for when you're using Auto IAM AuthN?

**Comment by enocom** [comment]
Another thought: have you checked what kind of traffic you have when you see these errors? Cf. https://cloud.google.com/sql/docs/postgres/authentication#restrictions (3000 logins / minute / instance).

**Comment by enocom** [comment]
How many IAM login attempts are you running per day and how many would fail? Ballpark is OK.

**Comment by carlpett** [comment]
It's... Quite a lot more that I expected! Or at least looking at the `New connection for "<instance>"` log from the proxy, which should be a decent metric for this? Not near 3k/minute, but it's around ~1-2/second, 140k total over the last 24h. Out of those we have 7-10 failures per day.

**Comment by enocom** [comment]
I don't think the team advertises an exact SLO for this, but if we're talking about 140k login attempts for which 10 fail that's less ~0.007%.

If you see those numbers go up a few orders of magnitude, I'd be happy to raise it with the team, but otherwise, I think you're just dealing with the usual vagaries of network services.
