### ISSUE TITLE
Please make the container image public and provide some examples

### ISSUE THREAD

**Issue by tcnghia** [GoogleCloudPlatform/cloud-sql-proxy#1380]
## Description

Currently the GCR repository isn't public:

```
❯ docker pull gcr.io/cloud-sql-connectors/cloud-sql-auth-proxy:2.0.0-preview.0             

Error response from daemon: manifest for gcr.io/cloud-sql-connectors/cloud-sql-auth-proxy:2.0.0-preview.0 not found: manifest unknown: Failed to fetch "2.0.0-preview.0" from request "/v2/cloud-sql-connectors/cloud-sql-auth-proxy/manifests/2.0.0-preview.0".

❯ docker pull gcr.io/cloud-sql-connectors/cloud-sql-auth-proxy:latest

Error response from daemon: manifest for gcr.io/cloud-sql-connectors/cloud-sql-auth-proxy:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/cloud-sql-connectors/cloud-sql-auth-proxy/manifests/latest".
```

Also, the public documentation mentions `$VERSION` should be used as image tags. However, it is unclear what format `$VERSION` should be (with the leading `v` like the Git version tag, or without?). Some examples would make this a lot clearer.

## Solution

Please make the GCR repo public and provide some examples to clarify the doc.

## Additional Context
Please reference any other relevant issues, PRs, descriptions, or screenshots here.

**Comment by enocom** [comment]
Would you mind trying one more time?

```
docker pull gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.0.0-preview.0
docker pull gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.0.0-preview.0-alpine
docker pull gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.0.0-preview.0-buster
```

I just tried from my non-work account and saw all three pull successfully.

**Comment by tcnghia** [comment]
Yep, that works for me. Thanks

**Comment by enocom** [comment]
Thanks for helping fix this @tcnghia. Sorry for the trouble.
