### ISSUE TITLE
Cloud functions (Gen 1) with 1.32.0 do not deploy.

### ISSUE THREAD

**Issue by RobHumphris** [GoogleCloudPlatform/cloud-sql-proxy#1407]
## Bug Description

Updated version from `1.31.2` to `1.32.0`
This brought in `golang.org/x/net v0.0.0-20220909164309-bea034e7d591`

Test ran locally without issue, but failed to deploy, error shown in stack trace.

I suspect that this may be due to Gen 1's Go version being pegged at 1.16.7

If I drop back to 1.31.2 then I have no problem with deployment.

## Example code (or command)

```
gcloud functions deploy ReprocessingDispatcher \
--region=${REGION} \
--project=${PROJ} \
--timeout=500s \
--runtime go116 \
--max-instances=1 \
--set-env-vars ${ENV_VARS},GCF=1,PAGE_SIZE=5 \
--trigger-http
```

## Stacktrace
```
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: # go.uber.org/atomic
vendor/go.uber.org/atomic/error.go:55:12: x.v.CompareAndSwap undefined (type Value has no field or method CompareAndSwap)
vendor/go.uber.org/atomic/error.go:61:24: x.v.Swap undefined (type Value has no field or method Swap)
vendor/go.uber.org/atomic/string.go:58:12: x.v.CompareAndSwap undefined (type Value has no field or method CompareAndSwap)
vendor/go.uber.org/atomic/string.go:64:12: x.v.Swap undefined (type Value has no field or method Swap); Error ID: 1a663392
```

## How to reproduce

  1. Update mod.go from `github.com/GoogleCloudPlatform/cloudsql-proxy v1.31.2` to `github.com/GoogleCloudPlatform/cloudsql-proxy v1.32.0`.
  2. Attempt to deploy.

## Environment

1. OS type and version: Google Cloud Function Gen 1.
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): 1.32.0

**Comment by enocom** [comment]
Thanks, Rob. For now, I'd recommend sticking with v1.32.2. It seems our most recent release has inadvertently updates transitive deps.

**Comment by enocom** [comment]
Side note: the Cloud SQL Go connector just went GA recently. We have a migration guide for moving from v1 to it here: https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/main/migration-guide.md. I'd recommend taking a look, as the new Go connector includes a bunch of new features missing from v1.

**Comment by RobHumphris** [comment]
FWIW, I did an experiment and found that I was able to deploy both Gen 1 & 2 Cloud Functions with Go v1.19 
![image](https://user-images.githubusercontent.com/220434/197855057-48cf0323-0563-482f-8019-a6945056c724.png)
Which suggests there is less need for backward compatibility than was thought.

**Comment by enocom** [comment]
Glad to hear it.
