### ISSUE TITLE
Add support for --quiet

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/cloud-sql-proxy#1452]
Environments that see lots of connections coming and going would benefit from a flag that limited logging to just errors.

**Comment by enocom** [comment]
@trajan0x Slightly unrelated, but are you using a client side connection pool in your application?

**Comment by trajan0x** [comment]
@enocom yeah, I'm doing some tweaking w/ idle connection settings around this now, but it's still fairly noisy

**Comment by enocom** [comment]
Either way, I think this is a worthwhile addition that needs to be in v2. I have a few things higher on my list, but this one is quickly coming up.
