### ISSUE TITLE
Is IAM authentication supported MySQL?

### ISSUE THREAD

**Issue by thgrw** [GoogleCloudPlatform/cloud-sql-proxy#1454]
## Question
I have been trying to get IAM authentication to work against a Cloud MySQL 5.7 DB, with some success. However it only works with versions prior to 1.28.1. The README says Postgres only, why is this? 

## Additional Context
Prior to this commit, https://github.com/GoogleCloudPlatform/cloud-sql-proxy/commit/e1386118ad239e6c1ff16df6f2be1351a6432bb3 I was able to get the IAM authentication working, but once this temporary trimming was remove it no longer works. I am not sure why this temporary fix was removed? It relates to this issue, but I can't see how it was permanently  fixed (https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/852).

This all relates to Postgres, but I guess there is a similar issue with MySQL

My setup is a remote server using cloud-sql-proxy to connect to a Cloud SQL server. I am using a dockerised version of sql-proxy started like this:

`docker run -d --rm --name cloud_proxy -v ./credential.json:/config.json -p 127.0.0.1:3306:3306 gcr.io/cloudsql-docker/gce-proxy:1.28.0 /cloud_sql_proxy -instances=[:INSTANCE:]=tcp:0.0.0.0:3306 -enable_iam_login -credential_file=/config.json`

This above works. Change it to 1.28.1 it doesn't.

**Comment by enocom** [comment]
@thgrw How are you logging in to your MySQL instance?

In short, MySQL does support manual IAM authentication where you provide an OAuth2 token with your IAM DB user. MySQL does not yet support automatic IAM authentication where you provide your IAM DB user and the proxy (with the `enable_iam_login` flag) will retrieve a token and insert it into the log in request for you and also refresh that token for future login requests.

**Comment by enocom** [comment]
> Prior to this commit, https://github.com/GoogleCloudPlatform/cloud-sql-proxy/commit/e1386118ad239e6c1ff16df6f2be1351a6432bb3 I was able to get the IAM authentication working, but once this temporary trimming was remove it no longer works. I am not sure why this temporary fix was removed? It relates to this issue, but I can't see how it was permanently fixed (https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/852).

When the Postgres feature rolled out, the server-side proxy didn't have support for longer OAuth2 tokens which can be up to 2048 bytes long. We added a temporary patch until the server side proxy added support for longer tokens. When that happens, the client side patch was unnecessary.

**Comment by thgrw** [comment]
> In short, MySQL does support manual IAM authentication where you provide an OAuth2 token with your IAM DB user. MySQL does not yet support automatic IAM authentication where you provide your IAM DB user and the proxy (with the `enable_iam_login` flag) will retrieve a token and insert it into the login request for you and also refresh that token for future login requests.

From the README and other resources, this is the behaviour I was expecting. However a colleague said he had managed to get the automatic login to work (with the enable_iam_login) and this seems true before 1.28.1. From my testing I was able to get the proxy to add the OAuth2 token and hence login to the database without any mysql password. Do you think this can be relied on, or is it more good luck and will only work under certain conditions?

Docker command used as above.

Mysql login:

`mysql -u iam_user -h 127.0.0.1`

Note the user needs to be the database user without the host part, just the name on its own.

In versions 1.28.1 and above you get error messages like:

`[Note] CloudSQL Instance's IAM access denied for user iam-user@test-db.iam.gserviceaccount.com: Error code :UNAUTHENTICATED Error Message :Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

 [Note] Access denied for user 'iam-user'@'cloudsqlproxy~1.1.x.x' (using password: YES)
`

Change the proxy to be 1.28.0 no error and you connect just fine.

**Comment by enocom** [comment]
That's an interesting discovery ;-)

For now, MySQL Auto IAM AuthN isn't officially supported, so I'd recommend against using it for production workloads. As soon as the feature is available, I will update the README.
