### ISSUE TITLE
Incorrect documentation leads to docker pull failing

### ISSUE THREAD

**Issue by thclark** [GoogleCloudPlatform/cloud-sql-proxy#1455]
## Bug Description

The docker pull command [stated here in the README doesn't work](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/42211090c4797b9e8751c2ee4e7ae8396ef1ebd5/README.md?plain=1#L359)

## Example code (or command)

```
docker pull gcr.io/cloud-sql-connectors/cloud-sql-auth-proxy:2.0.0-preview.0
```

## Stacktrace
```
Error response from daemon: manifest for gcr.io/cloud-sql-connectors/cloud-sql-auth-proxy:2.0.0-preview.0 not found: manifest unknown: Failed to fetch "2.0.0-preview.0" from request "/v2/cloud-sql-connectors/cloud-sql-auth-proxy/manifests/2.0.0-preview.0".
```

## How to reproduce

per above

## Environment

1. OS type and version: <YOUR_OS_HERE>
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): 2.0.0-preview.0 and 2.0.0-preview.1

## How to fix it

With some snooping I realised that the actual gcr repo is [here](https://console.cloud.google.com/gcr/images/cloud-sql-connectors/eu/cloud-sql-proxy) and that the following will work:
```
docker pull gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.0.0-preview.0
```

**Comment by enocom** [comment]
Thanks -- we went back and forth on the name. I'll fix this now.
