### ISSUE TITLE
GCE metadata not defined, using Workload Identity

### ISSUE THREAD

**Issue by cjyar** [GoogleCloudPlatform/cloud-sql-proxy#1516]
## Bug Description

The proxy is unable to start. It gives an error message ending with `GCE metadata "instance/service-accounts/default/token?scopes=https://www.googleapis.com/auth/sqlservice.admin" not defined`. This is in a cluster using Workload Identity.

## Example command

This is how the Deployment is running the proxy. Note this is `v2.0.0-preview.2`.

```yaml
        command:
        - /cloud-sql-proxy
        - -a=0.0.0.0
        - -l
        - PROJECT_ID:REGION:INSTANCE
```

## Output
```json
{"severity":"ERROR","timestamp":"2022-10-27T20:33:01.050Z","message":"The proxy has encountered a terminal error: unable to start: failed to get instance: Refresh error: failed to get instance metadata (connection name = \"PROJECT_ID:REGION:INSTANCE\"): Get \"https://sqladmin.googleapis.com/sql/v1beta4/projects/PROJECT_ID/instances/INSTANCE/connectSettings?alt=json&prettyPrint=false\": metadata: GCE metadata \"instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.admin\" not defined"}
```

## How to reproduce

I'm not certain; I have two GKE clusters in the same project, both configured similarly. One works, and the other gives this error.

## Environment

1. OS type and version: GKE 1.22.12-gke.2300
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): 2.0.0-preview.2

## Other information

As noted, this cluster is configured for Workload Identity. I ran `google/cloud-sdk:slim` using the same k8s ServiceAccount, and ran this within that container:
```
root@workload-identity-test:/# curl -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/
default/
GSA_NAME@PROJECT_ID.iam.gserviceaccount.com/
```
As shown, it gives the correct GSA name and project ID. So I believe Workload Identity is configured correctly.

I ran `gcloud projects get-iam-policy` and saw that this GSA is assigned the role `roles/cloudsql.client`.

I've tried several other versions of the proxy. I've gone through the [troubleshooting guide](https://cloud.google.com/kubernetes-engine/docs/troubleshooting/troubleshooting-security#workload-identity).

**Comment by enocom** [comment]
Thanks @cjyar. I'll investigate and report back here.

**Comment by enocom** [comment]
So one quick thought: have you checked with OAuth2 scopes are configured ok your nodes. Typically you’ll need a https://www.googleapis.com/auth/sqlservice.admin scope for the proxy to work. 

See https://stackoverflow.com/questions/69736586/how-to-add-an-configure-gke-node-pool-access-scope for example.

**Comment by enocom** [comment]
Here's what did:

I created a vanilla GKE cluster with Workload identity enabled and went through https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to. As part of the verification step I did this:

```
curl -H "Metadata-Flavor: Google" \
  http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https://www.googleapis.com/auth/sqlservice.admin
```

And got a valid token. Also, I verified the preview.2 works.

So there's some configuration on your one cluster that isn't right. For some context, the Proxy uses a SQL Admin API client under the hood, which requests a token from the metadata server with the `sqlserver.admin` scope.

I haven't seen the `GCE metadata server not defined` error before, but suspect you need to ensure workload identity is enable on both your cluster and your node pool.

**Comment by cjyar** [comment]
Thanks for the reply, @enocom. Starting to feel like this is out of scope for cloud-sql-proxy, except as it concerns useful error messages.

The curl command above produces `Unable to generate access token; IAM returned 404 Not Found: Not found; Gaia id not found for email GSA_NAME@PROJECT.iam.gserviceaccount.com`. It works in the working cluster, though. Both clusters have the same set of `oauthScopes`. I added the scope for `sqlservice.admin` to the test cluster, and it didn't change the behavior. I verified that the NAP node pool has the same scopes as the cluster, and that Workload Identity is enabled in the node pool as well as the cluster.

**Comment by enocom** [comment]
If you drop the scope query param off do you still get the 404?

**Comment by enocom** [comment]
Also have you checked that the named service account is an IAM member in your project?

**Comment by cjyar** [comment]
I was using the wrong GSA name! All my fault. Thanks for your patience @enocom.

However, it would be really great if cloud-sql-proxy could say, "No such user," instead of, "GCE metadata ... not defined."

**Comment by enocom** [comment]
Glad you sorted it out. :clap: 

This is one of those tricky cases where we can only surface the error message given to us by the compute library. It's not a great error message, I agree.
