### ISSUE TITLE
Recommend resource request/limits for cpu and memory when running in K8s

### ISSUE THREAD

**Issue by harkinj** [GoogleCloudPlatform/cloud-sql-proxy#1541]
## Question
Hi,
When deploying the image to K8s what are the  recommended request and limits settings for cpu and memory ?
Thanks for all info
John

**Comment by enocom** [comment]
We have an example here: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/examples/k8s-sidecar/proxy_with_workload_identity.yaml#L80.

As a start we recommend 1 CPU and 2 GiB. You’ll need to adjust both based on your IO and connection count.

**Comment by harkinj** [comment]
Perfect , thanks

**Comment by harkinj** [comment]
Perfect, thanjs
