### ISSUE TITLE
CPU hikes and won't come down on cloud-sql-proxy container, sometimes.

### ISSUE THREAD

**Issue by nurfgun** [GoogleCloudPlatform/cloud-sql-proxy#1553]
## Bug Description

Have found that the side-car proxy container SOMETIMES starts hogging all the cpu resource provided for it and won't let go. 

- CPU hikes to the limit and stays there.
- Memory usage stays very, very low.
- no special activity in logs both in the proxy container or in the one that uses it.
<img width="1653" alt="Screen Shot 2022-11-18 at 7 38 34 AM" src="https://user-images.githubusercontent.com/3580630/202575553-e31a62eb-4ac4-4323-898f-a629bb3b6e88.png">
<img width="1634" alt="Screen Shot 2022-11-18 at 7 42 49 AM" src="https://user-images.githubusercontent.com/3580630/202575920-454643cb-de7b-4599-9b59-af270775dca3.png">

These are what have tried :
- Tried more CPU (from 500m to 1 vcpu).
- Tried without http healthcheck. (does not seem to restart the container on this cpu hike with the http probe on. weird.)

It happens most when traffic starts going up after a long quite time.  (like 7 a.m. when users get up and start looking at our application before going to work. or 7 p.m. after users get off work, eat dinner.)

## Example code (or command)

```
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.0
          command: ["/cloud_sql_proxy",
                    # "-instances=project_id_hidden:asia-northeast3:cloudsql_id_hidden=tcp:3306,schoolbelle-ci:asia-southeast1:schoolbelle-singapore-cloudsql=tcp:3307",
                    "-instances=project_id_hidden:asia-northeast3:cloudsql_id_hidden=tcp:3306",
                    "-use_http_health_check",
                    "-term_timeout=30s",
                    "-credential_file=/secrets/cloud/google-service-account.json"]
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8090
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8090
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 1
          startupProbe:
            httpGet:
              path: /startup
              port: 8090
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 20                
          resources:
            limits:
              memory: "128Mi"
              cpu: "1"              
          volumeMounts:
            - name: cloud-credentials
              mountPath: /secrets/cloud
              readOnly: true

```

## Stacktrace
```
{"severity":"INFO","timestamp":"2022-11-17T17:16:18.000Z","caller":"proxy/client.go:239","message":"ephemeral certificate for instance project_id_hidden:asia-northeast3:cloudsql_id_hidden will expire soon, refreshing now."}
{"severity":"INFO","timestamp":"2022-11-17T17:16:18.002Z","caller":"proxy/client.go:203","message":"refreshing ephemeral certificate for instance project_id_hidden:asia-northeast3:cloudsql_id_hidden"}
{"severity":"INFO","timestamp":"2022-11-17T17:16:18.224Z","caller":"proxy/client.go:320","message":"Scheduling refresh of ephemeral certificate in 55m0s"}
{"severity":"INFO","timestamp":"2022-11-17T18:11:18.005Z","caller":"proxy/client.go:239","message":"ephemeral certificate for instance project_id_hidden:asia-northeast3:cloudsql_id_hidden will expire soon, refreshing now."}
{"severity":"INFO","timestamp":"2022-11-17T18:11:18.007Z","caller":"proxy/client.go:203","message":"refreshing ephemeral certificate for instance project_id_hidden:asia-northeast3:cloudsql_id_hidden"}
{"severity":"INFO","timestamp":"2022-11-17T18:11:18.400Z","caller":"proxy/client.go:320","message":"Scheduling refresh of ephemeral certificate in 55m0s"}
{"severity":"INFO","timestamp":"2022-11-17T19:06:18.005Z","caller":"proxy/client.go:239","message":"ephemeral certificate for instance project_id_hidden:asia-northeast3:cloudsql_id_hidden will expire soon, refreshing now."}
{"severity":"INFO","timestamp":"2022-11-17T19:06:18.007Z","caller":"proxy/client.go:203","message":"refreshing ephemeral certificate for instance project_id_hidden:asia-northeast3:cloudsql_id_hidden"}
{"severity":"INFO","timestamp":"2022-11-17T19:06:18.287Z","caller":"proxy/client.go:320","message":"Scheduling refresh of ephemeral certificate in 55m0s"}
{"severity":"INFO","timestamp":"2022-11-17T20:01:18.001Z","caller":"proxy/client.go:239","message":"ephemeral certificate for instance project_id_hidden:asia-northeast3:cloudsql_id_hidden will expire soon, refreshing now."}
{"severity":"INFO","timestamp":"2022-11-17T20:01:18.002Z","caller":"proxy/client.go:203","message":"refreshing ephemeral certificate for instance project_id_hidden:asia-northeast3:cloudsql_id_hidden"}
{"severity":"INFO","timestamp":"2022-11-17T20:01:18.338Z","caller":"proxy/client.go:320","message":"Scheduling refresh of ephemeral certificate in 55m0s"}
{"severity":"INFO","timestamp":"2022-11-17T20:56:18.004Z","caller":"proxy/client.go:239","message":"ephemeral certificate for instance project_id_hidden:asia-northeast3:cloudsql_id_hidden will expire soon, refreshing now."}
{"severity":"INFO","timestamp":"2022-11-17T20:56:18.006Z","caller":"proxy/client.go:203","message":"refreshing ephemeral certificate for instance project_id_hidden:asia-northeast3:cloudsql_id_hidden"}
{"severity":"INFO","timestamp":"2022-11-17T20:56:18.275Z","caller":"proxy/client.go:320","message":"Scheduling refresh of ephemeral certificate in 55m0s"}
{"severity":"INFO","timestamp":"2022-11-17T21:51:18.002Z","caller":"proxy/client.go:239","message":"ephemeral certificate for instance project_id_hidden:asia-northeast3:cloudsql_id_hidden will expire soon, refreshing now."}
{"severity":"INFO","timestamp":"2022-11-17T21:51:18.004Z","caller":"proxy/client.go:203","message":"refreshing ephemeral certificate for instance project_id_hidden:asia-northeast3:cloudsql_id_hidden"}
{"severity":"INFO","timestamp":"2022-11-17T21:51:18.298Z","caller":"proxy/client.go:320","message":"Scheduling refresh of ephemeral certificate in 55m0s"}
```

## How to reproduce

  1. deploy it as a sidecar
  2. have active containers use it
  

## Environment

1. OS type and version: Container-Optimized OS with containerd (cos_containerd) in gke version  of 1.23.10-gke.1000
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): 1.33.0 and 1.33.1 (tried both)
4. Proxy invocation: "/cloud_sql_proxy",
                    "-instances=hiding_project_id:asia-northeast3:hiding_sql_id=tcp:3306",
                    "-use_http_health_check",
                    "-term_timeout=30s",
                    "-credential_file=/secrets/cloud/google-service-account.json"

**Comment by enocom** [comment]
Typically CPU usage is bound to the amount of IO between a client and the Cloud SQL instance. Have you tried to correlate this CPU hike with application activity? How many active connections do you have when you see this?

Also side note: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/examples/k8s-sidecar/proxy_with_workload_identity.yaml#L78-L87.

**Comment by nurfgun** [comment]
> Typically CPU usage is bound to the amount of IO between a client and the Cloud SQL instance. Have you tried to correlate this CPU hike with application activity? How many active connections do you have when you see this?
> 
> Also side note: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/examples/k8s-sidecar/proxy_with_workload_identity.yaml#L78-L87.

If its about too many connections, shouldn't memory go up too as the note says?
We are using a connection pool approach with max connection limit set to 10 or 20(CPU in both show the same pattern) and log does not indicate any abnormal activity like creating a lot of connections at the moment of a CPU hike or within the range of time between CPU goes up and comes down (sometimes it comes down after about 1-2 hours on its own as the image below shows on the right. if it goes like that too long, I have been manually killing the pod - two drops on the left.)
 
<img width="796" alt="Screen Shot 2022-11-19 at 7 24 18 AM" src="https://user-images.githubusercontent.com/3580630/202813198-f66d6f8b-6e0f-40d4-82a8-af3f27ba8863.png">

Other observations are :
- sql querying activities in application used to stop working( and we received huge complaints from clients..haha) around the CPU hike.
- connections get reset every hour or so by cloudsql-proxy,  refreshing auth token.
- setting "keep-alive" option on( pinging periodically against dead connections caused by the ressetting) did prevent the application from freezing, but does not prevent the proxy container's CPU usage  from going up.

I am suspecting sending queries thru a dead connection may be related.. my two cents.

**Comment by enocom** [comment]
I set up our [sample app](https://github.com/GoogleCloudPlatform/golang-samples/tree/main/cloudsql/postgres/database-sql) and ran ~2 million requests (a mix of reads and writes) through it using the Proxy across 10 hours, and for good measure did this experiment twice over the weekend. In both cases, the Proxy's CPU usage was entirely normal.

There's always the possibility of some obscure bug in the Proxy code, but I suspect either an application problem (something is doing network IO against the Proxy), or perhaps a resource issue.

Here's what I'd suggest checking:

1. Is this problem happening across applications? Or is it just one application?
2. Can you confirm if your application isn't using the database connection when you see these CPU spikes?
3. And trying v2 as @kurtisvg suggests.

**Comment by nurfgun** [comment]
> I set up our [sample app](https://github.com/GoogleCloudPlatform/golang-samples/tree/main/cloudsql/postgres/database-sql) and ran ~2 million requests (a mix of reads and writes) through it using the Proxy across 10 hours, and for good measure did this experiment twice over the weekend. In both cases, the Proxy's CPU usage was entirely normal.
> 
> There's always the possibility of some obscure bug in the Proxy code, but I suspect either an application problem (something is doing network IO against the Proxy), or perhaps a resource issue.
> 
> Here's what I'd suggest checking:
> 
> 1. Is this problem happening across applications? Or is it just one application?
> 2. Can you confirm if your application isn't using the database connection when you see these CPU spikes?
> 3. Bumping the CPU and memory resource requests to see if that helps resolve the issue.
> 4. And trying v2 as @kurtisvg suggests.

1. Its been shown over two applications, one using a connection pool(mysql2), the other not. the other comes down from max CPU pretty quick if it ever spikes. so I haven't looked closely. I will attach an image of it at the bottom. 
2. Will add query counting, sending data and resulted data's size counting and watch until a spike appears.
3. Will. try bumping the CPU and memory x2 and x4 if the issue persists. (memory is barely under 10 mb though)
4. v2 will be tried last..hahah.
Thanks for the suggestion, @kurtisvg and @enocom  :)

during a pick time, 20-30 pods are spinned up. one or two jump up in CPU but down pretty quickly. 
<img width="804" alt="Screen Shot 2022-11-19 at 7 24 24 AM" src="https://user-images.githubusercontent.com/3580630/203169950-b468e1d9-4ee1-4a16-84d9-3e4df2680cbc.png">

**Comment by nurfgun** [comment]
> 2. Can you confirm if your application isn't using the database connection when you see these CPU spikes?

I have decided to watch select queries only since "update" and "delete" will not send or receive much encrypted data at all. correct me if I'm wrong. 

Select query counts per min for two pods:
<img width="1408" alt="Screen Shot 2022-11-22 at 4 04 02 PM" src="https://user-images.githubusercontent.com/3580630/203247376-0d6c3b96-93aa-4015-861b-9c99a0f55343.png">
returned data size per min(size by "JSON.stringify(rows).length") for two pods:
<img width="1411" alt="Screen Shot 2022-11-22 at 4 03 31 PM" src="https://user-images.githubusercontent.com/3580630/203247402-7c9db9b7-caba-4533-b87c-21f7d38944bb.png">
CPU usage for two pods:
<img width="875" alt="Screen Shot 2022-11-22 at 4 03 39 PM" src="https://user-images.githubusercontent.com/3580630/203247397-6e3bb929-5292-4f26-b58e-21e77634348d.png">

As you can see, two pods send and receive almost identically, but only CPU in one pod spikes.

I have decided that bumping CPU limits won't do much good if it's not based on connection load.
I'm skipping to number 4!

**Comment by nurfgun** [comment]
>And trying v2 as @kurtisvg suggests. 

Found that v2 have not solved the issue.

Here is what I have done and observed.
- switched cloudsql-proxy's version to 2.0.0-preview.3 at 2.15 PM.
- CPU spikes between 9-10 PM in all the two pods at the same time(syncronized!!?).
- Connection count and data size metrics between 9-10 PM do not seem much high compared to outher times.

So I'm out of answers. Any suggestions @enocom @kurtisvg  ?

What I might try :
- roll back to old versions like 1.7.x, which I had used for a long time for other applications.
- ditch mysql2's pool and go back to simple "create a connection for each query and kill it when done".



CPU spike between 9-10
<img width="802" alt="Screen Shot 2022-11-25 at 7 23 18 AM" src="https://user-images.githubusercontent.com/3580630/203870039-26d3622a-f19f-4c71-89de-3c02d34efa22.png">

Connection count metrics
<img width="1216" alt="Screen Shot 2022-11-25 at 7 23 08 AM" src="https://user-images.githubusercontent.com/3580630/203870042-aeada818-9442-4ea4-9642-d481bcc7000a.png">

data size metrics
<img width="1223" alt="Screen Shot 2022-11-25 at 7 22 56 AM" src="https://user-images.githubusercontent.com/3580630/203870044-e4f27c5e-f1e0-4821-a9be-3c5083a48ad0.png">

**Comment by kurtisvg** [comment]
@nurfgun Can you write a simple application that reproduces this behavior? As @enocom pointed out above, we're unable to replicate the same behavior, which points to something specific to your situation. If we can repro it, it's a bit easier for us to profile and identify the cause.

**Comment by enocom** [comment]
Separately, we should (and will) add pprof to v2.

**Comment by enocom** [comment]
@nurfgun Just added support for pprof in the latest commit. We'll be shipping a release soon and this will hopefully help understand what's happening here.

https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1564.

**Comment by nurfgun** [comment]
Since ditching pooling, servers have been running without a stop, or at least it looks so.
But we are spotting hikes in connection numbers in Google's cloud sql service since then.

So I'm thinking maybe 
- memory usage DOES NOT go up at all  or so negligible compared to CPU usage.
- Our code is somewhere causing too many connections that go unused since there is no change in disk read/write operations.

Sorry for the late response. now that we have the urgent element of the issue removed by removing pooling, I had to tend to other less but still urgent matters.

I will try pprof and report back.

Thanks guys.

**Comment by enocom** [comment]
You'll definitely want to have pooling in place. But if removing it helps debug, then that's at least somewhat good.

**Comment by enocom** [comment]
@nurfgun any updates here?

**Comment by enocom** [comment]
I'm going to close this as stale. Feel free to re-open with any new information.
