### ISSUE TITLE
Startup check fails on GKE

### ISSUE THREAD

**Issue by nurfgun** [GoogleCloudPlatform/cloud-sql-proxy#1555]
## Bug Description

With Sidecar setup with health check option on, health-check connection gets refused.

## Example code (or command)

```
        - name: cloudsql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.0.0-preview.3
          command: [
            "project_id_hidden:asia-northeast3:service_id_hidden?port=3306",
            "--health-check",
            "--http-port=8090",
            "--max-sigterm-delay=30s",
            "--credentials-file=/secrets/cloud/google-service-account.json",
          ]
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8090
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8090
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 1
          startupProbe:
            httpGet:
              path: /startup
              port: 8090
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 20                
          resources:
            requests:
              memory: "64Mi"
              cpu: "500m"        
            limits:
              memory: "64Mi"
              cpu: "500m"        
          volumeMounts:
            - name: cloud-credentials
              mountPath: /secrets/cloud
              readOnly: true
```

## Stacktrace
```
Startup probe failed: Get "http://xx.xx.xx.xx:8090/startup": dial tcp xx.xx.xx.xx:8090: connect: connection refused
```

## How to reproduce
- deploy it as a sidecar

## Environment
OS type and version: Container-Optimized OS with containerd (cos_containerd) in gke version of 1.23.10-gke.1000
Cloud SQL Proxy version (./cloud-sql-proxy --version): 2.0.0-preview.3
Proxy invocation:           
            "project_id_hidden:asia-northeast3:service_id_hidden?port=3306",
            "--health-check",
            "--http-port=8090",
            "--max-sigterm-delay=30s",
            "--credentials-file=/secrets/cloud/google-service-account.json",

**Comment by enocom** [comment]
You'll want to add the `--http-address=0.0.0.0` flag. By default we use `localhost` for people who might be using this in non-K8s contexts.

**Comment by nurfgun** [comment]
thank you! it's another change  in v2.

**Comment by enocom** [comment]
Added a note about this change in the migration guide. Thanks for all the bug reports.

https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1557.
