### ISSUE TITLE
Links for windows releases in README are incorrect

### ISSUE THREAD

**Issue by balys** [GoogleCloudPlatform/cloud-sql-proxy#1558]
## Description
There is a typo in links to download windows releases of the built version (in non $URL part):

https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/d8561d99f3fb4a5c2d085645c063c2f409113db0/README.md?plain=1#L141

https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/d8561d99f3fb4a5c2d085645c063c2f409113db0/README.md?plain=1#L151

incorrect: cloud-sql-proxy-x64.exe
correct: cloud-sql-proxy.x64.exe

## Solution
Change the URL accordingly

**Comment by enocom** [comment]
Thanks @balys! We'll fix this.
