### ISSUE TITLE
Add support for specifying the path to Unix socket per instance

### ISSUE THREAD

**Issue by hessjcg** [GoogleCloudPlatform/cloud-sql-proxy#1573]
## Bug Description
If you set the `unix-socket` parameter on a database instance, it should be the full path to the instance. In Proxy V2 preview 3, the instance name is appended to the value set for unix-socket. This is confusing.

## Expected Behavior
```
cloud-sql-proxy --unix-socket /var/csql myproject:us-central1:mydb
# listens on socket /var/csql/myproject:us-central1:mydb/.s.PGSQL.5432

cloud-sql-proxy myproject:us-central1:mydb?unix-socket=/var/mydb
# listens on socket /var/mydb/.s.PGSQL.5432
```

## Actual Behavior
```
# OK
cloud-sql-proxy --unix-socket /var/csql myproject:us-central1:mydb
# listens on socket /var/csql/myproject:us-central1:mydb/.s.PGSQL.5432

# BROKEN
cloud-sql-proxy myproject:us-central1:mydb?unix-socket=/var/mydb
# listens on socket /var/mydb/myproject:us-central1:mydb/.s.PGSQL.5432
```

## The Fix
The behavior of the existing `unix-socket` parameter defined globally or per-instance will remain unchanged. When unix-socket is set, it will  create a socket of the form "<unix-socket>/<instance name>" 

A new parameter `unix-socket-path`  will create paths of the form: "<unix-socket-path>". This new parameter may only be set per-instance. 

Postgres clients expect a socket address where the last element in the path is `.s.PGSQL.5432`. For Postgres database instances only, when unix-socket-path is set, the proxy will ensure that the last element of the path is `.s.PGSQL.5432`, adding  special path element if necessary. 

When both `unix-socket-path` and `unix-socket` are set, `unix-socket-path` will take precedence. 

If the socket path for one instance conflicts with the socket path for another instance, the proxy will print an error message and exit with an error code.

### Examples

| Database    |    Proxy CLI Arguments        |   Socket Path    | 
|---------|------------------------------------------------------------------------|--------------------------------------|
| mysql or mssql     |  --unix-socket /var/csql myproject:us-central1:mysqldb | /var/csql/myproject:us-central1:mydb |
| mysql or mssql    |  myproject:us-central1:mysqldb?unix-socket=/var/csql | /var/csql/myproject:us-central1:mydb |
| mysql or mssql    |  myproject:us-central1:mysqldb?unix-socket-path=/var/csql | /var/csql |
| mysql or mssql    |  --unix-socket /var/csql myproject:us-central1:mysqldb?unix-socket-path=/var/special | /var/special |
| pg          |  --unix-socket /var/csql myproject:us-central1:mysqldb | /var/csql/myproject:us-central1:mydb/.s.PGSQL.5432 |
| pg          |    myproject:us-central1:mysqldb?unix-socket=/var/csql  | /var/csql/myproject:us-central1:mydb/.s.PGSQL.5432 |
| pg           |   myproject:us-central1:mysqldb?unix-socket-path=/var/csql  | /var/csql/.s.PGSQL.5432 |
| pg           |   myproject:us-central1:mysqldb?unix-socket-path=/var/csql/.s.PGSQL.5432 | /var/csql/.s.PGSQL.5432 |
| pg    |  --unix-socket /var/csql myproject:us-central1:mysqldb?unix-socket-path=/var/special | /var/special/.s.PSQL.5432 |

**Comment by enocom** [comment]
Perhaps we add a `unix-socket-path` query param for instance-level configuration.

**Comment by enocom** [comment]
Also we could alias `unix-socket` to `unix-socket-dir` to make this a little more clear without a breaking change.

**Comment by enocom** [comment]
I'm open to adding support for a unix-socket-path parameter. But we can't break the behavior of unix-socket now that we're GA.

**Comment by hessjcg** [comment]
I agree. I've updated the description acordingly.
