### ISSUE TITLE
Build a distroless variant using ko or apko

### ISSUE THREAD

**Issue by jawnsy** [GoogleCloudPlatform/cloud-sql-proxy#1591]
## Feature Description

Build a minimal, distroless, container image using [the `ko` build tool](https://github.com/ko-build/ko) or [the related `apko` build tool](https://github.com/chainguard-dev/apko).

This removes all extraneous container contents, which reduces false positives that occur when other unrelated libraries are included in the base image. Additionally, it makes it easier to produce signed images or publish an SBOM.

**Comment by enocom** [comment]
Our default image actually already uses distroless. See [here](https://github.com/GoogleCloudPlatform/cloud-sql-proxy#container-images) and [here](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/Dockerfile#L29).

For signed images, we're considering https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1267. If you have thoughts on what that should look like, please add them to the issue.

Assuming you're not thinking of something else that I've missed, I'm going to close this. Feel free to re-open if our current distroless container needs some work.

**Comment by jawnsy** [comment]
Thanks for triaging and the links! I think documentation would be useful to help people choose between the images, based on the README description, it seems that the default distroless variant would be preferable for us, over alpine.
