### ISSUE TITLE
Possible incorrect classifaction of log messages: classifed as ERROR should be INFO

### ISSUE THREAD

**Issue by harkinj** [GoogleCloudPlatform/cloud-sql-proxy#1609]
Hi,
We see the below  in our logs but it is logged to stderr and also it has log severity of ERROR and it polluting out logs.
There are similar messages which we see and think they should all be INFO.
Any way this can be changed?
We are already using  -log_debug_stdout=true but as these log messaged are classified as ERROR it has no affect.
Thanks
John

**2023/01/06 12:06:40 ephemeral certificate for instance XXXXXXXX:us-central1:in-home-qa will expire soon, refreshing now.**

**Comment by enocom** [comment]
The log message there is a verbose log. Pass `--verbose=false` on your CLI invocation to turn this off. Meanwhile, we've cleaned up the logging significantly in v2 which will go GA this month. I'd suggest trying out the new version as well.
