### ISSUE TITLE
Cloud SQL Proxy refreshing connections from localhost constantly

### ISSUE THREAD

**Issue by MorenoMdz** [GoogleCloudPlatform/cloud-sql-proxy#1610]
## Bug Description

Cloud SQL Proxy when deployed with Docker to Render.com keeps refreshing connections from the local network.

External connections work fine but this is not the expected behavior, we don't have any other service running that is listening to this port, I even tried to change the port to something random, like 13370 in the example below, but the connection keeps refreshing.

## Example code (or command)

```
Jan 12 12:38:50 PM  2023/01/12 15:38:50 Listening on 0.0.0.0:13370 for our_connection_instance
Jan 12 12:38:50 PM  2023/01/12 15:38:50 Ready for new connections
Jan 12 12:38:50 PM  2023/01/12 15:38:50 Generated RSA key in 66.655533ms
Jan 12 12:38:55 PM  2023/01/12 15:38:55 New connection for "our_connection_instance"
Jan 12 12:38:55 PM  2023/01/12 15:38:55 refreshing ephemeral certificate for instance our_connection_instance
Jan 12 12:38:55 PM  2023/01/12 15:38:55 Scheduling refresh of ephemeral certificate in 54m59s
Jan 12 12:38:55 PM  2023/01/12 15:38:55 Client closed local connection on 10.105.44.110:13370
Jan 12 12:39:00 PM  2023/01/12 15:39:00 New connection for "our_connection_instance"
Jan 12 12:39:00 PM  Your service is live 🎉
Jan 12 12:39:00 PM  2023/01/12 15:39:00 Client closed local connection on 10.105.44.110:13370
Jan 12 12:39:05 PM  2023/01/12 15:39:05 New connection for "our_connection_instance"
Jan 12 12:39:05 PM  2023/01/12 15:39:05 New connection for "our_connection_instance"
Jan 12 12:39:05 PM  2023/01/12 15:39:05 Client closed local connection on 10.105.44.110:13370
Jan 12 12:39:05 PM  2023/01/12 15:39:05 Client closed local connection on 10.105.44.110:13370
Jan 12 12:39:10 PM  2023/01/12 15:39:10 New connection for "our_connection_instance"
Jan 12 12:39:10 PM  2023/01/12 15:39:10 Client closed local connection on 10.105.44.110:13370
Jan 12 12:39:15 PM  2023/01/12 15:39:15 New connection for "our_connection_instance"
Jan 12 12:39:15 PM  2023/01/12 15:39:15 Client closed local connection on 10.105.44.110:13370
Jan 12 12:39:20 PM  2023/01/12 15:39:20 New connection for "our_connection_instance"
Jan 12 12:39:20 PM  2023/01/12 15:39:20 Client closed local connection on 10.105.44.110:13370
Jan 12 12:39:25 PM  2023/01/12 15:39:25 New connection for "our_connection_instance"
Jan 12 12:39:25 PM  2023/01/12 15:39:25 Client closed local connection on 10.105.44.110:13370
Jan 12 12:39:30 PM  2023/01/12 15:39:30 New connection for "our_connection_instance"
Jan 12 12:39:30 PM  2023/01/12 15:39:30 Client closed local connection on 10.105.44.110:13370
Jan 12 12:39:35 PM  2023/01/12 15:39:35 New connection for "our_connection_instance"
Jan 12 12:39:35 PM  2023/01/12 15:39:35 New connection for "our_connection_instance"
Jan 12 12:39:35 PM  2023/01/12 15:39:35 Client closed local connection on 10.105.44.110:13370
Jan 12 12:39:35 PM  2023/01/12 15:39:35 Client closed local connection on 10.105.44.110:13370

```

## How to reproduce

  1. Start the proxy server with this dockerfile
```
# Cloud Sql Proxy
FROM alpine as proxy
WORKDIR /usr/src/app
COPY credentials.json /secrets/cloudsql/credentials.json

## When running local in an M1 you need to use an ARM compatible image that may not have apk add, use apt-get if needed
# RUN apt-get update && apt-get install --no-install-recommends -y wget
RUN apk add wget
RUN wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
RUN chmod +x cloud_sql_proxy
```

## Environment

1. OS type and version: Linux Alpine amd64
4. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): latest from docker
5. Proxy invocation (for example, `./cloud-sql-proxy --enable_iam_login --dir /path/to/dir INSTANCE_CONNECTION_NAME`): `./cloud_sql_proxy -credential_file=/secrets/cloudsql/credentials.json -instances=our_connection_instance=tcp:0.0.0.0:13370`

**Comment by MorenoMdz** [comment]
For context, in Render.com each of our processes is running in dedicated services, the cloud proxy is running in an internal service and we have a NestJS server that connects to it. I tried to have the node server target a different port and even shut down that server completely as it is a staging environment, but the connections kept refreshing in the auth proxy.

**Comment by enocom** [comment]
@MorenoMdz Are you referring to the "New Connection ..." / "Client closed local connection..." logs?

**Comment by MorenoMdz** [comment]
> @MorenoMdz Are you referring to the "New Connection ..." / "Client closed local connection..." logs?

Yes @enocom, those are happening constantly, every 5 seconds or so

**Comment by MorenoMdz** [comment]
Closing this one, it seems that Render has a health check that runs every 5s on the first port it finds open 🙃 , I will have to figure out a way to keep that health check annoyance away from the proxy connections.

**Comment by enocom** [comment]
Glad you figured it out. :smile: The Proxy does have support for healthchecks too. Perhaps you could pointer Render at that?
