### ISSUE TITLE
GCR image missing for v2.0.0

### ISSUE THREAD

**Issue by gpomykala** [GoogleCloudPlatform/cloud-sql-proxy#1632]
v2.0.0 was migrated to Go1.19, which is a great thing, especially that v1.x version images run on Go 1.17 with reported CVEs.
However, there is no v2.0.0 image available to this day. I see that few untagged images were pushed to GCR on the day of v2.0.0 release, however the latest tagged GCR image is v1.33.2
https://console.cloud.google.com/gcr/images/cloudsql-docker/GLOBAL/gce-proxy
![image](https://user-images.githubusercontent.com/5765120/216546006-efa5bc0c-4bee-4b39-baea-f280cc41b799.png)
Could someone push the v2.0.0 image to GCR or tag existing image, if it is already there?

**Comment by enocom** [comment]
We renamed the image as part of v2. See https://github.com/GoogleCloudPlatform/cloud-sql-proxy#container-images for where you can find it.
