### ISSUE TITLE
403 Authorisation error with auth proxy ...

### ISSUE THREAD

**Issue by michealroberts** [GoogleCloudPlatform/cloud-sql-proxy#1651]
## Question

So, I have authenticated with my gcloud account with the usual method, and verified have I authorised my default app engine service account with cloud.

I have added the Cloud SQL Client role to my service account.

However, when attempting to connect to a Cloud SQL instance with the usual:

```bash
./cloud-sql-proxy --address 0.0.0.0 --port 3306 $PROJECT_NAME:$REGION:$INSTANCE_NAME
```

I am seeing the following error:

```
The proxy has encountered a terminal error: unable to start: failed to get instance: Refresh error: failed to get instance metadata (connection name = "***"): googleapi: Error 403: The client is not authorized to make this request., notAuthorized
```

I have redacted the connection name for security reasons.

Essentially, the jist of my question is thus: I have followed all of the steps in the documentation, but I can not connect. How do I debug this 403 issue?

## Additional Context

I see in the overview of my instance, the service account listed with is associated to the MySQL instance is not one I recognise: currently, it looks to be:

```
p****************-******@gcp-sa-cloud-sql.iam.gserviceaccount.com
```

I'm not sure if that is what is causing the error? But I have no way of changing this or accessing this IAM user? (It seems to be listed in the same $PROJECT_ID as what I have for my IAM account.

This whole setup is sooooo confusing.

**Comment by michealroberts** [comment]
Ok, no sooner have I asked -> I read the manual a little deeper. I needed the following:

```
./cloud-sql-proxy --address 0.0.0.0 --port 3306 $PROJECT_NAME:$REGION:$INSTANCE_NAME --gcloud-auth 
```

Where it will use the default gcloud auth credentials.

Hallelujah why wasn't this documented more clearly! :D

**Comment by enocom** [comment]
The `--gcloud-auth` flag will use your gcloud user credentials as opposed to application default credentials. Generally, we recommend avoiding `--gcloud-auth` and instead using application default credentials.

You can set those up with:

```shell
gcloud auth application-default login
```

This will place a credential is a well-known location that all the Google Cloud Libraries use.
