### ISSUE TITLE
Do we have to specify a database with IAM authencation?

### ISSUE THREAD

**Issue by yu-iskw** [GoogleCloudPlatform/cloud-sql-proxy#1661]
### Question

When I connect to a postgres database in Cloud SQL without IAM authentication via `cloud-sql-proxy`, I don't have to specify a target database. However, if I try to connect one with IAM authentication, I'm not able to connect it in my experience. Is there any way to connect to Cloud SQL with IAM authentication via `cloud-sql-proxy` without specifying a database?

**Comment by enocom** [comment]
By default, Postgres clients will typically connect to the postgres database if you don't specify one.

When you're trying to connect with an IAM user, I would guess that your IAM user doesn't have permission to read the postgres database, and so the connection fails. If you update the permissions and give your IAM user access, then this should work.

Hope that helps.
