### ISSUE TITLE
Add support for metrics / tracing

### ISSUE THREAD

**Issue by chainlink** [GoogleCloudPlatform/cloud-sql-proxy#169]
Hi,
It would be great to be able to track metrics from the proxy (connections, disconnects, etc) in prometheus. If you're open to a PR on this, I can create one

**Comment by hfwang** [comment]
We intend to add metrics to the proxy, we were thinking of first starting with pushing metrics to stackdriver, but it makes sense to try to make it pluggable so others can write to different places.

**Comment by hfwang** [comment]
Just wanted to reach back out on this issue, we plan to add monitoring to the proxy client using the OpenCensus library which has pluggable exports.

Nothing yet that we are ready to show publicly though.

**Comment by chainlink** [comment]
Great news! @hfwang any idea on ETA for that?

**Comment by tanuck** [comment]
If there's work already underway for this, is there an ETA yet?

**Comment by hfwang** [comment]
We are hoping to have something available in October. The proxy client allows for some interesting setups that are a bit hard to express with the existing stackdriver library, namely reporting metrics to multiple projects simultaneously (as you could connect to instances in different projects).

**Comment by hfwang** [comment]
Sorry for the delay, we had hoped to get something done by October. We had built a prototype, but actually getting it to a releasable state has dragged on quite a bit. We are still working on this though.

**Comment by oliveiraVG** [comment]
Any updates on this issue?

**Comment by sergio-fleetsmith** [comment]
Is progress still being made on this front? Would love to have metrics for CloudSQL to see performance and be able to debug potential issues.

**Comment by kishendas** [comment]
Is there any progress on this one ? We definitely need metrics for CloudSQL, as its in our critical path.

**Comment by marcosrmendezthd** [comment]
+1

**Comment by jbradleynh** [comment]
Hoping this feature is underway, metrics from cloudsql-proxy would be super valuable

**Comment by mariolameiras** [comment]
@hfwang Any progress on the possibilty of having metrics?

**Comment by elsbrock** [comment]
You could use the `stackdriver_exporter` as workaround.

**Comment by bergquist** [comment]
@hfwang Any thoughts about how you want to implement this? I'd love to see support for Prometheus. Esp if I can get error/success rates for queries.

**Comment by kurtisvg** [comment]
@bergquist to clarify, the proxy only touches the connection layer (and not the protocol layer). 

You would see metrics around how often connections connect / disconnect but wouldn't see things like what queries were performed or if they were successful for not.

**Comment by enocom** [comment]
Note: this issue likewise includes support for Cloud Trace. See #600 for context.

**Comment by withnale** [comment]
Any update on this? I'd love to see this feature but it seems to keep getting knocked back due to some dependency or other? 

Can we not separate the metrics and tracing cards and get them delivered independently?

**Comment by enocom** [comment]
I agree this is one of the top feature requests.

At the moment, we're a little hesitant to add support for metrics and tracing given [the state of the two](https://github.com/census-instrumentation/opencensus-go#opencensus-and-opentracing-have-merged-to-form-opentelemetry-which-serves-as-the-next-major-version-of-opencensus-and-opentracing-opentelemetry-will-offer-backwards-compatibility-with-existing-opencensus-integrations-and-we-will-continue-to-make-security-patches-to-existing-opencensus-libraries-for-two-years-read-more-about-the-merger-here) in the Go ecosystem. Presently, we're waiting on two things:

1. Some major refactoring of the dialer functionality in the proxy (work currently in progress), and
2. [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-go#project-status) to go GA.

The refactoring will make adding support for metrics and tracing much, much less painful.

**Comment by enocom** [comment]
See https://github.com/kurtisvg/cloud-sql-go-connector#enabling-tracing where we've added support for tracing and metrics in the [new dialer](https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/870).

**Comment by enocom** [comment]
The v2 release (currently in public preview) has support for Prometheus, Cloud Monitoring, and Cloud Trace.

Get the release here: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/releases/tag/v2.0.0.preview.0.

Docs here: https://github.com/GoogleCloudPlatform/cloud-sql-proxy#support-for-metrics-and-tracing.
