### ISSUE TITLE
Connection to postgresql fails

### ISSUE THREAD

**Issue by MohithSarvepalli** [GoogleCloudPlatform/cloud-sql-proxy#1701]
<img width="1792" alt="Screenshot 2023-03-16 at 9 43 14 AM" src="https://user-images.githubusercontent.com/61641808/225512600-36fa6e9b-8298-461f-9197-741d57aa95ea.png">
### Question

How do I grant select privilege to user?
Iam getting this error when trying to run "terraform apply"
could not start transaction: read tcp 100.64.0.1:64725->34.172.78.93:5432: read: connection reset by peer

### Code

```Go
main.tf
resource "google_sql_database_instance" "instance" {
  name             = "my-database-instance"
  region           = "us-central1"
  database_version = "POSTGRES_14"
  settings {
    tier = "db-g1-small"
  }

  deletion_protection = "true"
}
resource "google_sql_database" "database" {
  name     = "my-database"
  instance = google_sql_database_instance.instance.name
}
resource "google_sql_user" "mohith" {
  name     = "<USER>"
  instance = google_sql_database_instance.instance.name
  password = "<PASSWORD>"
}
resource "postgresql_grant" "readonly_tables" {
  database    = google_sql_database_instance.instance.name
  role        = "mohith"
  schema      = "public"
  object_type = "table"
  privileges  = ["SELECT"]
}
terraform {
  required_providers {
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = "1.18.0"
    }
  }
}

provider "google" {
  # Configuration options
  project     = "<MY_PROJECT>"
  region      = "us-central1"
  zone        = "us-central1-a"
  credentials = "keys.json"
}
provider "postgresql" {
  host             = "<PUBLIC_IP>"
  username         = "<USER>"
  password         = "<PASSWORD>"
  expected_version = "10.1"
}
```

**Comment by enocom** [comment]
By default, Cloud SQL prevents any traffic from the public internet to your instance. Meanwhile, the Postgres provider assumes a Postgres database is reachable at the Public IP you've provided.

The easier way around this is to run the Cloud SQL Proxy on localhost and point the Postgres provider at it, e.g.,

``` shell
./cloud-sql-proxy <INSTANCE_CONNECTION_NAME> --port 5432 # starts a listener on localhost:5432
```

Then:

``` hcl
provider "postgresql" {
  host             = "127.0.0.1"
  username         = "<USER>"
  password         = "<PASSWORD>"
  expected_version = "10.1"
}
```

**Comment by MohithSarvepalli** [comment]
But, my host id is not that I want to access, Can you please elaborate on this, anyways I tried this, now I see different error-
 Error: could not start transaction: pq: SSL is not enabled on the server

**Comment by MohithSarvepalli** [comment]
So, anyways , I resolved this error. But I have a db where I need to use tunneling for connecting to db, so, how should I configure the provider, so that, I could grant privileges to user.In this the user is being created, but when granting privileges, Iam getting connection timed out.

**Comment by enocom** [comment]
I’d suggest looking at the Postgres provider docs. Since this isn’t a Proxy issue, I’d suggest asking on StackOverflow if you’re still stuck.
