### ISSUE TITLE
confusing error mesage

### ISSUE THREAD

**Issue by aleksandersumowski** [GoogleCloudPlatform/cloud-sql-proxy#1764]
### Bug Description

When authorizing using gcloud user credentials any failure is considered to be an error to read profile file. The type of error is not checked:
https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/b9572fe30725c2491d0bfaa3399451e6f0494eef/internal/gcloud/gcloud.go#L67

but other failure modes are possible. In our case proxy is running in an environment without network connectivity to the Google APIs and this is what's causing authorization to fail.

### Example code (or command)

```
// paste your code or command here
```

### Stacktrace

```bash
2023-04-21 05:56:14,882 INFO spawned: 'cloudsqlproxy' with pid 845
{"severity":"INFO","timestamp":"2023-04-21T05:56:14.895-0400","message":"Authorizing with gcloud user credentials"}
2023-04-21 05:56:15,896 INFO success: cloudsqlproxy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
{"severity":"ERROR","timestamp":"2023-04-21T05:56:17.092-0400","message":"The proxy has encountered a terminal error: unable to start: error initializing dialer: error reading config: exit status 1; stderr was:\nWARNING: Could not open the configuration file: [$HOME/.config/gcloud/configurations/config_default].\nERROR: (gcloud.config.config-helper) You do not currently have an active account selected.\nPlease run:\n\n  $ gcloud auth login\n\nto obtain new credentials.\n\nIf you have already logged in with a different account:\n\n    $ gcloud config set account ACCOUNT\n\nto select an already authenticated account to use.\n"}
2023-04-21 05:56:17,098 INFO exited: cloudsqlproxy (exit status 1; not expected)
```

### Steps to reproduce?

1. Run cloud_sql_proxy with restricted network
2. Try to authenticate using user credentians

### Environment

1. OS type and version:
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): 2.0.0
3. Proxy invocation command: /usr/local/bin/cloud_sql_proxy -l -a 0.0.0.0 -p PORT 'CONNECTION_STRING' -i -g --impersonate-service-account SERVICE_ACCOUNT

**Comment by jackwotherspoon** [comment]
Hi @aleksandersumowski, 

Thanks for raising an issue on the Cloud SQL Proxy! 😄 

I will happily look into the issue for you and see if we can potentially make some better error messages. Before I do I have a few clarifying questions I hope you can answer for me.

I was wondering if you could double-check and clarify which version of the Cloud SQL Proxy you are running? The reason I ask is because `--enable_iam_login` and `--dir` are not supported flags for the v2 proxy. These are flags that are only supported in v1 of the Proxy, you can see the v2 equivalent for these flags in the [migration guide](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/migration-guide.md). 
You also mentioned in the steps to reproduce: 
> 1. Run cloud_sql_proxy with restricted network

Running `cloud_sql_proxy` is used in v1 only and the new binary is `cloud-sql-proxy` for v2. Maybe you are accidentally running a v1 version of the proxy you have installed? 

I would recommend trying the v2 equivalent of the invocation command you mentioned which would be:
```shell
./cloud-sql-proxy --auto-iam-authn --unix-socket /path/to/dir INSTANCE_CONNECTION_NAME
```

Let me know if this command still produces a similar error message and if it does I will happily investigate further.

Have a great day! 😃

**Comment by enocom** [comment]
Looks like you're starting the proxy with `--gcloud-auth` (which is a legacy flag that we don't recommend). Have you tried invoking the proxy using Application Default Credentials?

**Comment by aleksandersumowski** [comment]
I'm not in control of the setup: this is operated by other team. The version is 2.0.0, checked with `--version`

**Comment by aleksandersumowski** [comment]
Is the codepath that I've pointed to only used in legacy workflow?

**Comment by aleksandersumowski** [comment]
I haven't actually updated the invocation from the sample one. The one we use is a result of fairly convoluted bash script. Sorry! If you do think it's relevant I'll look into it on Monday

**Comment by aleksandersumowski** [comment]
Updated it now, it's `/usr/local/bin/cloud_sql_proxy -l -a 0.0.0.0 -p PORT 'CONNECTION_STRING' CAUTH` 

where CAUTH must stand for the role/account? 🤔

**Comment by enocom** [comment]
Positionally the proxy would interpret CAUTH as another instance connection name. The error message above implies you’re setting a CSQL_PROXY_GCLOUD_AUTH environment variable if you’re not setting the flag. I’d recommend avoiding that and trying again.

**Comment by aleksandersumowski** [comment]
The problem I'm reporting is not the not being able to authenticate using proxy. I know how to do it: fix the network route. The problem I'm reporting is that even though it's a networking issue the log message in the output of the proxy is suggesting issue with reading a profile file.

**Comment by aleksandersumowski** [comment]
The environmental variable CSQL_PROXY_GCLOUD_AUTH doesn't seem present. But worked out that CAUTH likely stands for `-i -g --impersonate-service-account SERVICE_ACCOUNT`

**Comment by aleksandersumowski** [comment]
So the whole invocation is:
`/usr/local/bin/cloud_sql_proxy -l -a 0.0.0.0 -p PORT 'CONNECTION_STRING' -i -g --impersonate-service-account SERVICE_ACCOUNT`

**Comment by enocom** [comment]
A-ha. Try leaving off the `-g` flag -- that tells the Proxy to use gcloud user auth, which is a legacy flag and not something we recommend. If you run the Proxy without the flag, it will do the thing that every other Google Cloud client library does and use application default credentials. I'd imagine that will solve  your problem.

**Comment by aleksandersumowski** [comment]
My problem was solved by opening network connectivity to google apis on port 988. The responsible team will update authentication method will migrate the authentication method to Application Default Credentials. If you don't want to/can't fix the error message here, please close the issue

**Comment by enocom** [comment]
As far as I can tell, the error message is telling you that your gcloud config isn't valid, which is a valid error message. If you see a confusing error message after the auth change, feel free to re-open with more details.

**Comment by aleksandersumowski** [comment]
The error message is saying `Could not open the configuration file: [$HOME/.config/gcloud/configurations/config_default]` which is not the reason why the proxy wasn't getting authenticated

🤷

**Comment by enocom** [comment]
What makes you think so? I see only the errors pasted above.

**Comment by aleksandersumowski** [comment]
I didn't touch anything the file or the container that was running proxy. The change that fixed the issue was opening the port. So the issue wasn't with opening of the configuration file

**Comment by enocom** [comment]
Hmmm. That probably means it's a gcloud API call that's failing with an odd error, which is also out of scope here.

If you remove the `-g` flag and try again, do you get a better error?
