### ISSUE TITLE
cloud-sql-proxy draws a distinction between "localhost" and "127.0.0.1" within a docker context

### ISSUE THREAD

**Issue by digitalnomd** [GoogleCloudPlatform/cloud-sql-proxy#1771]
### Question

I'm getting the following error while using `cloud-sql-proxy` and `alembic` together, and trying to connect to my Cloud SQL instance within a docker environment (note that this is an error coming from `alembic`):

```
(2003, "Can't connect to MySQL server on 'localhost' ([Errno 99] Cannot assign requested address)")
```

What is strange is that I don't get this error when I use `127.0.0.1`, which `cloud-sql-proxy` is listening on. `localhost` should be using the loopback address and resolve to `127.0.0.1` but it doesn't.

Both processes, (`cloud-sql-proxy` and `alembic`) are running within the same docker container so their loopback should be the same.

**Comment by enocom** [comment]
We do bind to `127.0.0.1` by default instead of `localhost`. You might also check your container's `/etc/hosts` file, although I'd expect `localhost` to resolve.

**Comment by digitalnomd** [comment]
The issue ended up being in the way we were setting the configuration for SQLAlchemy's alembic migration tool.

**Comment by enocom** [comment]
Would you mind elaborating? Curious why a configuration might do this.

**Comment by digitalnomd** [comment]
I have code that's running the cloud-sql-proxy in a sub process with a randomized available port.

Alembic is then run once this is running and needs to use that port and localhost to retrieve a connection pool.

If the port isn't passed to the environment or set properly then alembic will be unable to connect to the database.

In my case I was setting the environment variable with the port but it was getting overrides by alembic for some reason. It most likely has to do with how the tool provides a way to set the environment. The fix in my case was to set the URL in the alembic configuration before calling it which prevented that port from being overwritten.

**Comment by enocom** [comment]
Thanks for the clarification. I'll close this, but if you see an opportunity to improve anything here, let me know.
