### ISSUE TITLE
SIGTERM with no active connections should result in 0 exit code

### ISSUE THREAD

**Issue by n1koo** [GoogleCloudPlatform/cloud-sql-proxy#1803]
### Feature Description

We have an issue where airflow detects non-zero exit code as a problem in KubernetesPodOperator. Digging deeper to the recent changes in V2 it seems like we moved from 0 to 143 in the case of sigterm.

However this behaviour is curious when all connections etc are gracefully terminated within the time period. There is really no issue so shutdown should result in 0 (imho).

Whats the reasoning behind having `143` always?

### Alternatives Considered

I was reading https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1529#issuecomment-1308118348 and would like to avoid `/quitquitquit`. And I also cant really figure out why using the endpoin is 'better' than SIGTERM?

**Comment by n1koo** [comment]
Hi @hessjcg you are absolutely right - 143 is the correct signal. However in my experience its one of those things that are rarely done in real world and thus surprises like with Airflow KPO tend to happen when they just look at non-zero being error. See eg [airflow](https://github.com/apache/airflow/blob/17e5e7b3b0ceae9f7e25bbee2d4beb62a9aaab39/airflow/providers/cncf/kubernetes/triggers/pod.py#L236)

We already do use `/quitquitquit` to signal Istio with a fork of https://github.com/karlkfi/kubexit but trying to avoid building more complexity in tooling to just to nudge out a wanted signal. Intent on our side is really to get rid of things like `kubexit` - not build more logic to it 

Its a fair point though that maybe i'm looking at this backwards and really the change should be on `Airflow` side _but_ i'm guessing Airflow is not the only system doing the non-zero checking.

I was gonna first propose that maybe this behaviour should also be tunable, atleast for a period, like `keep_old_exit_code_behaviour` flag (not a great name but for clarity of idea :) ) - but that that sort of complexity would also not be great on your side.

I think in our case we just gotta have to revert back to v1 for the KPO workloads or patch more logic to `kubexit` until Airflow has a fix come in

**Comment by enocom** [comment]
We'd use the conventional behavior by default but at least make it possible to work around all the places the Proxy is used and not following exit code conventions.

**Comment by n1koo** [comment]
I also realised that this impacts even k8s own `CronJobs` causing restarts

Eg a test cronjob succeeding with 1 spinning down:

```manual-run-niko-n9cg7                           3/3     Running           0          47s   10.55.18.41    gke-nonprod-us-east1-expanded-node-po-347889d8-44gp   <none>           <none>
manual-run-niko-n9cg7                           0/3     Error             0          52s   10.55.18.41    gke-nonprod-us-east1-expanded-node-po-347889d8-44gp   <none>           <none>
manual-run-niko-n9cg7                           0/3     Completed         1 (7s ago)   54s   10.55.18.41    gke-nonprod-us-east1-expanded-node-po-347889d8-44gp   <none>           <none>
```

```    
Last State:     Terminated
      Reason:       Error
      Exit Code:    143
      Started:      Mon, 22 May 2023 16:18:41 +0300
      Finished:     Mon, 22 May 2023 16:18:55 +0300
```

**Comment by n1koo** [comment]
Oh and sorry to pipe more here but also on the topic of what is graceful termination. When using `/quitquitquit` we are throwing `ERROR` level message in https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/v2.2.0/cmd/root.go#L761

So eg. `{"severity":"ERROR","timestamp":"2023-05-22T13:46:50.011Z","message":"The proxy has encountered a terminal error: /quitquitquit received request"}`

This probably shouldnt be ERROR but INFO

**Comment by enocom** [comment]
So just to clarify, you don't want to use the Proxy's `/quitquitquit`  endpoint and instead want `SIGTERM` to result in a 0 exit code?

**Comment by n1koo** [comment]
Yes, exactly so. I verified with `kubexit` that the `/quitquitquit` works as intended but really would prefer to not have to use such addons/workarounds.

I'm actually bit curious that since the scope is also normal k8s `Job`s nobody else has brought this up before - but a lot of users should be impacted

**Comment by enocom** [comment]
I think most folks are using `/quitquitquit` now. But making that easier seems like a good idea.

**Comment by timothystewart6** [comment]
I am also seeing it exit with ERROR, rather than INFO.

You can test this easily from cli:

`./cloud-sql-proxy INSTANCENAME --quitquitquit`

```
2023/06/16 16:37:36 The proxy has started successfully and is ready for new connections!
2023/06/16 16:37:36 Enabling quitquitquit endpoint at localhost:9091
```

from another terminal 

`curl -X POST localhost:9091/quitquitquit`


```
2023/06/16 16:38:08 The proxy has encountered a terminal error: /quitquitquit received request
```

A flag for exiting with `0` would be great so we don't need to use `/quitquitquit`, but fixing the existing endpoint to exit with `0` would be great in the meantime.  Exit code `143` stinks when running this in k8s because the pod exits with an error, which isn't expected (although `143` is correct).

**Comment by enocom** [comment]
I believe that's just where the error message is going which we've fixed here: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1806. We'll have this out in the next release on Tuesday.

**Comment by enocom** [comment]
See here for confirmation: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/cmd/errors.go#L34.

**Comment by smart-commerce-tim** [comment]
@enocom great!  Thank you so much!  Can't wait, no more failed pods in k8s!

**Comment by timothystewart6** [comment]
@enocom great! Thank you so much! Can't wait, no more failed pods in k8s!

**Comment by enocom** [comment]
We'll still add a flag to exit zero on sigterm separately here, but that will probably be in the following release (next month).

**Comment by timothystewart6** [comment]
Thank you so much!

**Comment by timothystewart6** [comment]
Oddly, we are still getting `Error with exit code 143`  in k8s when using `gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.4.0` and calling `quitquitquit`

**Comment by timothystewart6** [comment]
> Oddly, we are still getting `Error with exit code 143` in k8s when using `gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.4.0` and calling `/quitquitquit`

I think I have an idea of how this is still happening but correct me if I am wrong.  We use `/quitquitquit` as a `preStop` lifecycle hook in k8s to call the admin endpoint, however the binary is also listening for `SIGTERM`  https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/cmd/errors.go#L28. I am assuming that it's not replacing it with exit code 0, some how `143` is still winning. Hoping the flag is added soon as we can always for a `0` when exiting cleanly.

**Comment by enocom** [comment]
@hessjcg would you mind taking a look?

We might have missed something here, but if something calls the `/quitquitquit` endpoint, the Proxy is going to exit with a 0 exit code. If somehow, a SIGTERM is getting to the Proxy first, you wouldn't get a 0 exit code.

**Comment by enocom** [comment]
We'll have this out in the next release on Tuesday.

**Comment by timothystewart6** [comment]
Thank you!
