### ISSUE TITLE
Proxy assigns random port for PostgreSQL 15 instances

### ISSUE THREAD

**Issue by CyberHippo** [GoogleCloudPlatform/cloud-sql-proxy#1816]
### Bug Description

Hi,
The current documentation says that the proxy will automatically detect the default database engine's port and start a corresponding listener.
However after upgrading an existing Cloud SQL PostgreSQL instance from `v14.5` to `v15`, the proxy assigns a random port instead of the default port (`5432`).
I suspect that the proxy fails to automatically detect the engine of PostgreSQL v15 instances.

### Steps to reproduce?

1. Upgrade an existing Cloud SQL PostgreSQL instance from `v14.5` to `v15`
2. Run the proxy against that instance using the INSTANCE_CONNECTION_NAME
3. Random port get assigned instead of `5432`

### Environment

1. OS type and version: `20.04.6 LTS (Focal Fossa)`
2. Cloud SQL Proxy version: `cloud-sql-proxy version 2.3.0+linux.amd64`
3. Proxy invocation command: `./cloud-sql-proxy INSTANCE_CONNECTION_NAME`

### Additional Details

I know that I could specify the `--port` flag to prevent a random port from being assigned.

**Comment by jackwotherspoon** [comment]
Hi @CyberHippo Thanks for raising this issue! I will take a try at reproducing this and see if I can come up with a fix if need be.

Have a great day!

**Comment by jackwotherspoon** [comment]
Hi @CyberHippo I just attempted to reproduce this using the same version of the Proxy as you and everything worked fine for me, with the proxy using port 5432 for my Postgres 15 instance.

```sh
./cloud-sql-proxy my-project:my-region:my-instance
2023/05/26 17:19:34 Authorizing with Application Default Credentials
2023/05/26 17:19:34 [my-project:my-region:my-instance] Listening on 127.0.0.1:5432
2023/05/26 17:19:34 The proxy has started successfully and is ready for new connections!
```

**Comment by CyberHippo** [comment]
Hi @jackwotherspoon , Thank you for your time. 
The proxy now correctly assigns the port. I guess that when the instance was freshly updated, the port got randomized.
I'll close this issue for now and might reopen it if I find a way to reproduce it.

Have a great day!
