### ISSUE TITLE
Tag 'latest-alpine', 'latest-buster', '1', '2', '2-alpine', '2.3-alpine', '2-buster', '2.3-buster' images

### ISSUE THREAD

**Issue by ryboe** [GoogleCloudPlatform/cloud-sql-proxy#1820]
### Feature Description

I'm using the `alpine` version of `cloud-sql-proxy`. I would like to always pull the latest v2 version of the container, but there's no way to do that. Adding these tags would make it easier for users to decide how to weigh the risk of updating vs. the risk of falling behind:

```
1
1.33
2
2.3
2-alpine
2.3-alpine
2-buster
2.3-buster
latest-alpine
latest-buster
```

**Comment by enocom** [comment]
Thanks for the suggestion @ryboe. I think it's a reasonable proposal and we'll work it into our upcoming backlog.

**Comment by enocom** [comment]
Sorry we've let this slip through the cracks. I'll make sure we have it for the next release.

**Comment by enocom** [comment]
This is done. Thanks @jackwotherspoon for getting this over the line.

**Comment by enocom** [comment]
![image](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/assets/1175430/74add84c-cb1e-4af7-8a55-552300e49cf0)
