### ISSUE TITLE
The 'latest' release still points at v1 instead of v2

### ISSUE THREAD

**Issue by ryboe** [GoogleCloudPlatform/cloud-sql-proxy#1821]
### Bug Description

The actual latest release of cloud-sql-proxy is currently v2.3.0, but anyone fetching the latest release from the GitHub API today will get v1.33.7.

![image](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/assets/1250684/ceca29c6-00ed-4770-a735-1bd259a4eba0)

I understand that moving the `latest` tag will cause breakages for some, but anyone fetching the `latest` release artifacts has assumed that risk.

Perhaps the tag could be moved in phases 🤷 
1. Create an issue about the tag move, with guidance about how to pin to a v1 release.
2. Move the tag from v1.33.7 to v2.3.0 for 5 minutes, then move it back.
3. Refer cranky users to the issue from 1
4. Wait a bit
5. Move the tag from v1.33.7 to v2.3.0 for 30 minutes, then movie it back
6. Refer cranky users to the issue from 1
7. Wait a bit
8. Move the tag from v1.33.7 to v2.3.0 forever
9. There are no more cranky users because they all updated their code
10. Profit!

**Comment by enocom** [comment]
The root issue here is that we renamed the underlying image as part of releasing v2.

Compare:

```
# v1
gcr.io/cloudsql-docker/gce-proxy
```

vs

```
# v2
gcr.io/cloud-sql-connectors/cloud-sql-proxy
```

So while it does create some work to upgrade to v2,

**Comment by ryboe** [comment]
I should've been more clear that I'm referring to the `Latest` GitHub release. The `latest` docker image tag correctly points at the `2.3.0` image. However, when I was making GitHub API calls, it told me the latest release was `v1.33.7`. Since [it's currently not possible to pull the latest v2.x.x image](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1820), I tried to get the latest v2 version from the GitHub API. That's when I found that `Latest` refers to v1.33.7, which you can see in the right column of the main repo page.

![latest_cloud_sql_proxy_release_is_old](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/assets/1250684/c5ef2fef-5af6-4439-aacd-40915026bbe6)

**Comment by enocom** [comment]
I’ve updated the releases to fix the latest tag. Does this look the way you’d expect now?

**Comment by ryboe** [comment]
Yes it does! Thank you so much! 👏 🎉

**Comment by enocom** [comment]
Thanks for pointing this out. We will always be marking v2 as latest going forward.
