### ISSUE TITLE
v1 Go Connector misreports version

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/cloud-sql-proxy#1836]
In the v1 Go Connector, there is a hardcoded version:

https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/v1/proxy/certs/certs.go#L40

Instead, the v1 Go Connector should respect the version here:

https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/v1/cmd/cloud_sql_proxy/version.txt

**Comment by jackwotherspoon** [comment]
Fixed as part of #1904 and #1900
