### ISSUE TITLE
Missing Documentation on Maxiumum # of Instances 

### ISSUE THREAD

**Issue by cbeauch** [GoogleCloudPlatform/cloud-sql-proxy#1845]
### Description

Hey, 

I'm curious on the maximum number of connections that the proxy can support? I can't seem to find anything other than that multiple connection strings are supported. 
I need to connect to roughly 30 different SQL instances for constant data streaming. Will this cause any issues or extra latency?

**Comment by jackwotherspoon** [comment]
Hi @cbeauch, thanks for raising a great question on the Cloud SQL Proxy! 😄 

In terms of max connections (`--max-connections` [flag](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/51cc2c6b4d5b369cb99f1a18fe679610b4f184e8/cmd/root.go#L387)), and the number of instances that can be connected to by a single invocation, the Cloud SQL Proxy defaults to unlimited. So in theory you should be able to configure and connect to all 30 instances at once. However, in my experience I can't say that I have personally tried that many instances in a single workload.

Each instance configured would be listening on its own individual port and the Proxy performs refreshes asynchronously in the background, so ideally you should see minimal/no latency.

I would love if you could let us know how it goes and if you run into any issues. If you do we can file an issue to enhance the use of the Proxy at scale.

@enocom is currently out for the week but once he is back we will discuss how we can better document this across our README and Google Cloud docs.

Thanks again and have a great day!

**Comment by cbeauch** [comment]
Thanks for the reply! 

I actually did try it about a year ago and **thought** I was noticing some latency (with kafka) and ended up creating 3 separate proxy machines to split up the work load. 

However, I didn't actually look too much into it. I plan on trying again this month and can report back.

**Comment by enocom** [comment]
To answer the question here, there is no maximum number of instances that the Proxy stops working with. However, it's important to understand how the Proxy scales. We have some [docs here](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/examples/k8s-sidecar/proxy_with_workload_identity.yaml#L79-L87).

In short:

more connections = more memory
more throughput = more CPU

If you have lots of memory and CPU, you can configure the Proxy to handle as many connections as you like. However, in most cases, you probably want to balance load across multiple proxy processes.

Can you tell me a bit more about how your workload looks? Typically, I'd expect to see one Proxy process per workload.

**Comment by cbeauch** [comment]
Thanks @enocom! 

I am using Kafka Connect to stream from each database. One Kafka instance with 30 DB connectors. Each connector uses only 1 proxy instance. The throughput for majority of the databases is extremely low. 

At the moment, I have 3 proxy VM's, so ~10 proxy instances on each. These proxy VM's are the smallest that GCP has to offer and I see no latency issues currently.

**Comment by enocom** [comment]
Where does the Kafka Connector run relative to the Cloud SQL Proxy? Are they on the same VM, or does traffic cross VMs?

**Comment by cbeauch** [comment]
Not on the same VM at the moment. Kafka VM -> Proxy VMs -> DB. It's not load balanced either, it's just Connector X always to  VM1, Connector Y always to VM2, etc. 

So next week I'll have Cloud SQL Proxy on the same VM as the Kafka and see how it goes. Resources shouldn't be a problem but if I notice latency I'll just go another route.
