### ISSUE TITLE
Make connection failures non-fatal

### ISSUE THREAD

**Issue by jawnsy** [GoogleCloudPlatform/cloud-sql-proxy#1854]
### Feature Description

Errors to refresh ephemeral certificates are currently fatal, even when specifying multiple instances. This means that a single instance being unavailable will cause a complete outage of all databases backed by a given proxy instance.

In this case, I think that it would be preferable to:

* Emit a warning and reject connections for the specific instance if necessary
* Continue serving traffic for other instances backed by the same proxy
* Retry the connection on demand when a connection to the proxy is established (e.g. if instance A corresponds to port 5432 on the proxy while instance B corresponds to port 5433, then connections to port 5432 should cause the ephemeral certificate to be refreshed if necessary, including re-attempts)

As a user, this would be my desired behavior:

1. Instance `foo` is in stopped state, instance `bar` is running
2. cloud-sql-proxy starts with instance `foo` bound to port 5432 and `bar` bound to port 5433
   * Currently, cloud-sql-proxy will stop with an error message
   * My desired behavior is to have cloud-sql-proxy start anyways (possibly with a warning message indicating that the certificate cannot be refreshed for `foo` because it is stopped)
3. When connecting to port 5432, it would be reasonable for the proxy to refuse the connection, since `foo` is stopped
4. Suppose that someone then starts instance `foo`
5. On the next connection to port 5432, or on the next certificate refresh cycle, the proxy should detect that the database is now running and refresh certs

### Sample code

```
// sample code here
```

### Alternatives Considered

We can use separate proxies for each instance, so that `foo` being stopped will only affect one of the proxies, and other ones will work normally. This is obviously more work to manage.

### Additional Details

At the moment, the reliability of systems backed by cloud-sql-proxy will be the logical conjunction of all instances (that is, for systems connecting to database instances A, B, both A and B must be operational for the proxy to be operational), when it would be preferable for the reliability to be the logical disjunction of all instances (that is, for systems connecting to database instances A, B, the proxy will be operational if either A or B are operational)

Here's a simple reproduction (with project/instance names anonymized); in this scenario, `example-project:us-east1:example-instance-foo` is stopped while `example-project:us-east1:example-instance-bar` is running.

```shell-session
$ ./cloud-sql-proxy --version
cloud-sql-proxy version 2.4.0+darwin.arm64

$ ./cloud-sql-proxy --auto-iam-authn 'example-project:us-east1:example-instance-foo' 'example-project:us-east1:example-instance-bar'
2023/06/21 08:00:43 Authorizing with Application Default Credentials
2023/06/21 08:00:44 could not resolve version for "example-project:us-east1:example-instance-foo": fetch ephemeral cert failed: Refresh error: create ephemeral cert failed (connection name = "example-project:us-east1:example-instance-foo"): googleapi: Error 409: The instance or operation is not in an appropriate state to handle the request., invalidState
2023/06/21 08:00:44 The proxy has encountered a terminal error: unable to start: [example-project:us-east1:example-instance-foo] Unable to mount socket: fetch ephemeral cert failed: Refresh error: create ephemeral cert failed (connection name = "example-project:us-east1:example-instance-foo"): googleapi: Error 409: The instance or operation is not in an appropriate state to handle the request., invalidState
```

**Comment by jackwotherspoon** [comment]
Hi @jawnsy thanks for the detailed feature request! 😄 

This sounds like a very promising idea, especially in a production environment with connections to many Cloud SQL instances. The re-starting/stopping of an instance could cause a refresh to fail and be fatal to the entire deployment as you pointed out. This is not ideal, as once the instance re-starts it would be successful on the next refresh attempt. 

I will discuss with the team how this feature might look like and update this issue with any ideas or progress.

Thanks again for the detailed issue, have a great day!

**Comment by enocom** [comment]
This is a great idea @jawnsy. We have a bunch of stuff in our upcoming backlog, but we'll add this to the list of things to get to soon.

**Comment by enocom** [comment]
For TCP sockets, there's a way to make this work today if you specify the ports for the Proxy:

``` shell
./cloud-sql-proxy \
  'example-project:us-east1:example-instance-foo?port=5432' \
  'example-project:us-east1:example-instance-bar?port=5433'
```

That will make the Proxy avoid trying to retrieve instance metadata until someone connects. When someone connects and the upstream connection fails, the Proxy will log an error but otherwise stay up.

For Unix sockets, this doesn't work because the Proxy has to know if it's a Postgres instance or not (to add the appropriate Postgres socket suffix). To fix this, we might want to port a feature from v1: [`skip_failed_instance_config`](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/v1/cmd/cloud_sql_proxy/cloud_sql_proxy.go#L118-L122). In that case, the behavior would be: if someone specifies a Unix socket, we try to check metadata and otherwise skip it if we can't. There's not a good way to automatically heal in this case, but if that's desired, then using FUSE would be better.

**Comment by annafang-google** [comment]
One question regarding the implementation. v1 uses the flag skip_failed_instance_config to prevent proxy from exiting on bad instance specification. In v2, the default behaviour for specified tcp port is already matching the non fatal behaviour. Should we just make it a default behaviour for unix socket and unspecified tcp port without using the flag?

**Comment by enocom** [comment]
> Should we just make it a default behaviour for unix socket and unspecified tcp port without using the flag?

I think that's a great idea. We log loudly when a unix socket fails to mount, but otherwise don't kill the Proxy.

**Comment by enocom** [comment]
Closing this as fixed per https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1854#issuecomment-1699725187.
