### ISSUE TITLE
Any release date for the next version?

### ISSUE THREAD

**Issue by chenjr0719** [GoogleCloudPlatform/cloud-sql-proxy#1910]
### Question

Is there any schedule/date for the next release?
There is a vulnerability has been identified on the Go 1.20.6, which is used to build the latest release of cloud sql proxy.
https://pkg.go.dev/vuln/GO-2023-1987

And it is already fixed on the 1.20.7 or 1.21. It could be nice if we can have a new release so that I can fix this vulnerability on my application.

**Comment by jackwotherspoon** [comment]
@chenjr0719  We will be releasing new version of the Proxy later today that is built against Go 1.21 🚀

**Comment by enocom** [comment]
We've discovered a last minute minor fix to include in this release and will be cutting a new version tomorrow.

For what it's worth, the Proxy isn't affected by https://pkg.go.dev/vuln/GO-2023-1987.
