### ISSUE TITLE
Allow configuration of unix socket path

### ISSUE THREAD

**Issue by devnore** [GoogleCloudPlatform/cloud-sql-proxy#1917]
### Feature Description

When using sockets there is the distinct possibility that the socket's full path will exceed the maximum length of (108 chars) 

This limit is easy to hit as the connectionName used in the socket structure is a combination of 
ProjectID, Region & SQL instance name

## Current limitations
- ProjectID
  - 6 to 30 chars 
  - reference: https://cloud.google.com/resource-manager/reference/rest/v1/projects#:~:text=The%20unique%2C%20user%2Dassigned%20ID,Trailing%20hyphens%20are%20prohibited.
- Region
  - 8 to 23 chars
  - reference 
    ```for i in $(gcloud compute regions list --format='value(name)'); do echo "${#i} => ${i}"; done | sort -n```
- Instance Name 
  - The total length of project-ID:instance-ID must be 98 characters or less. 
  - reference https://cloud.google.com/sql/docs/postgres/instance-settings
- Socketfile
  -  .s.PGSQL.5432 => 13

## ConnectionName Worst case (The Issue):

- ProjectID: 30
- Region: 23
- Socketfile: 13
- Instance Name: 98-1-30 = 67

given the current format: `/{ProjectID}:{Region}:{Instance Name}/{Socketfile} `
` 1 + 30 + 1 + 23 + 1 + 67 + 1 + 13  = 137`
left over for --unix-socket path 
` 108 - 137 = -29 `

Even before considering the path to the socket, this exceeds the max socket length of 108 chars

## Proposal 1
Add an option `--socket-structure` to change the dir structure to one of the following `--socket-structure="simple|md5|sha256|..."`

#### Pros:
- Human readable
#### Cons:
- Variable length

#### Example: Worst case
- publicIP|PrivateIP: xxx.xxx.xxx.xxx => 15 chars
- ProjectID: 30
- Socketfile: 13

given the format: /{ProjectID}/{IP}/{Socketfile} 
` 1 + 30 + 1 + 15 + 1 + 13 = 61 `
left over for --unix-socket path 
` 108 - 61 = 47 `

#### Pros:
- Fixed length
#### Cons:
- Not human readable

- md5sum: 32
- Socketfile: 13

given the format: /{md5sum}/{Socketfile} 
` 1 + 32 + 1 + 13 = 47 `
left over for --unix-socket path 
` 108 - 47 = 61 `

#### Pros:
- Fixed length
#### Cons:
- Not human readable
- less chars for --unix-socket path

- md5sum: 64
- Socketfile: 13

given the format: /{md5sum}/{Socketfile} 
` 1 + 64 + 1 + 13 = 79 `
left over for --unix-socket path 
` 108 - 79 = 29 `

This would have a fixed length for the socket regardless of naming as md5 will generate a sum with length 32

## Proposal 2
Same scenario as Proposal 1 but keeps the original structure and create symlinks to shorter paths

this would require some more cleanup when disconnecting but would be more human-readable

**Comment by enocom** [comment]
Thanks for the suggestion. We might already have a nice way to solve this.

Have you tried the `unix-socket-path` query param?

https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/cmd/root.go#L176-L184

**Comment by devnore** [comment]
> Thanks for the suggestion. We might already have a nice way to solve this.
> 
> Have you tried the `unix-socket-path` query param?
> 
> https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/cmd/root.go#L176-L184

Awsome! This will solve my immediate issue
