### ISSUE TITLE
Error: cannot specify --auto-iam-authn and --token without --login-token

### ISSUE THREAD

**Issue by Joaobranquinho** [GoogleCloudPlatform/cloud-sql-proxy#1939]
### Question

Hello everyone!

I've been trying to connect to a database instance online using cloud-sql-proxy.
I have a valid token as a source of IAM credentials. I'm also trying to use `--auto-iam-authn` so that no extra authentication is rqueired.

when I do this I get the following error.
```
Error: cannot specify --auto-iam-authn and --token without --login-token
```

What am I supposed to use as `--login-token` in this case?
From my understanding nothing else is required given that I'm already impersonating the right service accont when setting `--token`

Thank you in advance

**Comment by jackwotherspoon** [comment]
Hi @Joaobranquinho, thanks for the question! If you are using the Proxy with `--token` and `--auto-iam-authn` flags then you must also set the `--login-token`. 

The Cloud SQL Auth Proxy uses two different tokens/credential objects. One (`--token`) is used for authorization and makes sure the IAM Principal running the Proxy has the proper IAM permissions to connect, requires the "https://www.googleapis.com/auth/sqlservice.admin" scopes. The second (`--login-token`) is used for IAM database authentication and is used as the password for automatic IAM database authentication, requires the "https://www.googleapis.com/auth/sqlservice.login" scope.

These two tokens should be for the same IAM principal, just require different scopes. You can try setting the same token for `--login-token` that you are using for service account impersonation with the `--token` flag.

**Comment by enocom** [comment]
I addition to what Jack said, I’d be curious to hear why you’re using a token instead of the usual application default credentials.

**Comment by Joaobranquinho** [comment]
> These two tokens should be for the same IAM principal, just require different scopes. You can try setting the same token for `--login-token` that you are using for service account impersonation with the `--token` flag.

This worked like a  charm. Thanks!

> I addition to what Jack said, I’d be curious to hear why you’re using a token instead of the usual application default credentials.

Its a token to a service account. Avoid giving developers excessive permissions. Developers get to execute a cloud function that a hole new set of permissions. 
I went with token to avoid the hole key management hassle

**Comment by jackwotherspoon** [comment]
Hi @Joaobranquinho! 

Glad it worked! 

> Its a token to a service account. Project users get to execute a cloud function, that uses said service account, that has a hole new set of permissions. I went with token to avoid the hole key management hassle

By default the Application Default Credentials for Cloud Functions will be set to the [runtime service account](https://cloud.google.com/functions/docs/securing/function-identity#runtime_service_account), which means you most likely can remove the need for `--token` and `--login-token` and set your Cloud Function to run using your custom service account. We usually recommend this approach over using the token flags.

**Comment by pocesar** [comment]
for people hitting the wall, this is how you're supposed to use it (think that Docker knows nothing about `--auto-iam-authn` flag)

```bash
docker run --rm --network=host gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.6.1 \
--address 0.0.0.0 \
--port 5432 \
--token=$(gcloud auth print-access-token) \
--login-token=$(gcloud sql generate-login-token) \
--auto-iam-authn \
$(gcloud sql instances describe MY_INSTANCE --format='value(connectionName)')
```

**Comment by enocom** [comment]
That works. Alternatively, you could mount your application default credentials in the container and skip all the token stuff entirely.

```
docker run \
-v PATH_TO_ADC_KEY:/key.json \
--rm \
--network=host gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.6.1 \
--address 0.0.0.0 \
--port 5432 \
--auto-iam-authn --credentials-file /key.json \
$(gcloud sql instances describe pg --format='value(connectionName)')
```

Granted you might have to adjust file permissions on your key.
