### ISSUE TITLE
Explicitly open port 9090 on the cloud-sql-proxy sidecar for k8s to hit the health check endpoints 

### ISSUE THREAD

**Issue by ryanvilbrandt** [GoogleCloudPlatform/cloud-sql-proxy#1943]
### Description

The [documentation for adding health checks](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/tree/main/examples/k8s-health-check#running-cloud-sql-auth-proxy-with-health-checks-in-kubernetes) to the cloud-sql-proxy sidecar is mostly very complete and well-written, and gave good guidance on the how and why of the whole process.

However, after implementing the example chart as shown, Kubernetes was not able to hit the health checks on the default port 9090, so the pods were constantly being killed and rebuilt, leaving the whole deployment unhealthy.

### Potential Solution

My final solution was to explicitly open port 9090 on the cloud-sql-proxy sidecar:

```
          ports:
            - name: cloud-sql-proxy
              containerPort: 9090
              protocol: TCP
```

I do not have complete knowledge of my Kubernetes setup, so there may be something hidden in the configuration that changed the default behavior such that I experienced my issue above. However, I'd like to see the example code updated to include explicitly opening that port, as it may save many other people a similar headache if they're in my situation.

### Additional Details

Kubernetes version: 1.25

**Comment by jackwotherspoon** [comment]
Thanks for the suggestion! Assigning to @hessjcg who is our resident Kubernetes expert.

**Comment by ryanvilbrandt** [comment]
Looks good, thank you!

**Comment by hessjcg** [comment]
I'm also updating the Cloud SQL Proxy Operator. [PR #442](https://github.com/GoogleCloudPlatform/cloud-sql-proxy-operator/pull/442)
