### ISSUE TITLE
Include 3rd party licenses in the published container images

### ISSUE THREAD

**Issue by hessjcg** [GoogleCloudPlatform/cloud-sql-proxy#1966]
### Feature Description

We should distribute copies of this license as well as all 3rd party licenses in software distribution bundles like container images. 

The cloud-sql-proxy-operator downloads all 3rd party licenses and bundles them into the container image. We could do something similar in this repo. See: [cloud-sql-proxy-operator/Makefile](https://github.com/GoogleCloudPlatform/cloud-sql-proxy-operator/blob/0e0bb40339f5d4ea2659f81cc4f55ea15a2e3938/Makefile#L172)

**Comment by enocom** [comment]
Fixed in https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/2141.
