### ISSUE TITLE
Unclear how to connect using libpq/psycopg2 via Cloud SQL Auth Proxy

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [GoogleCloudPlatform/cloud-sql-proxy#1991]
### Question

Am trying to connect to a Postgres Instance with IAM Auth enabled (through Cloud SQL Auth Proxy with auto Workload Identity)
Tried:
1. supplying a password. Fails with:
   > password authentication failed for user "codecov-api@foo.iam"
2. supplying no password. Fails with:
   > fe_sendauth: no password supplied 

Is there any way to make connecting work?

Env set to `true` on Proxy are:
- `CSQL_PROXY_HEALTH_CHECK`
- `CSQL_PROXY_PRIVATE_IP`
- `CSQL_PROXY_PROMETHEUS`
- `CSQL_PROXY_STRUCTURED_LOGS`
- `CSQL_PROXY_AUTO_IAM_AUTHN`

**Comment by enocom** [comment]
Have you verified your setup with this? https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#verify_the_setup

What you'll want to see if that your workload identity matches the user you have in your database.

**Comment by AndreasBergmeier6176** [comment]
> What you'll want to see if that your workload identity matches the user you have in your database.

Thanks. These were mismatching.

**Comment by enocom** [comment]
Glad to hear it.

**Comment by AndreasBergmeier6176** [comment]
What would be great btw. is to have a flag to allow only passwordless connects via proxy and fail with a detailed error message if the connect cannot be done passwordless.

**Comment by enocom** [comment]
The Proxy isn't protocol aware, so we can't read the database account out of the request or the response. But we could probably print the active service account in the logs possible -- I know we do something like this when a credentials file is in use. That would at least highlight who the Proxy is running as.

**Comment by enocom** [comment]
Looks like we just report the file location of the credentials. Reporting the active IAM user  is possible, but would require some work to address credential types x environment (Cloud Run, GCE, GKE, etc).

https://pkg.go.dev/cloud.google.com/go/compute/metadata#Email might be useful.
