### ISSUE TITLE
Support INSTANCE_CONNECTION_NAME as environment variable

### ISSUE THREAD

**Issue by w32-blaster** [GoogleCloudPlatform/cloud-sql-proxy#2019]
### Feature Description

In version 1.x of the proxy there was a way to use the INSTANCES environment variable which is somewhat similar to the INSTANCE_CONNECTION_NAME in version 2.x 
Setting INSTANCE_CONNECTION_NAME through environment variable would make more sense because its cleaner and let us have better integration way into kubernetes

### Sample code

```
export INSTANCE_CONNECTION_NAME="myproject:my-region:mysql?port=3307;myproject:my-region:mysql-2?port=3308"
./cloud-sql-proxy
```

**Comment by enocom** [comment]
Thanks @w32-blaster. Let me quickly investigate what v1 does versus v2 and report back here.

**Comment by enocom** [comment]
So v1 doesn't support environment variables. I think you're saying this works:

```
export INSTANCE_CONNECTION_NAMES="myproject:my-region:mysql?port=3307;myproject:my-region:mysql-2?port=3308"
./cloud_sql_proxy instances=$INSTANCE_CONNECTION_NAMES
```

For v2, we have a simpler option:

```
export CSQL_PROXY_INSTANCE_CONNECTION_NAME_0="myproject:my-region:mysql?port=3307"
export CSQL_PROXY_INSTANCE_CONNECTION_NAME_1="myproject:my-region:mysql-2?port=3308"

./cloud-sql-proxy
```

Does that solve your use case?

**Comment by w32-blaster** [comment]
From the v1 readme:
```
[Connection Flags](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/tree/v1#connection-flags)
[-instances="project1:region:instance1,project3:region:instance1"](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/tree/v1#-instancesproject1regioninstance1project3regioninstance1)
A comma-separated list of instances to open inside -dir. Also supports exposing a TCP port and renaming the default Unix Domain Sockets; see examples below. Same list can be provided via INSTANCES environment variable, in case when both are provided - proxy will use command line flag.
```
See the last sentence. 

Are you suggesting that we can set as many CSQL_PROXY_INSTANCE_CONNECTION_NAME_x as we want, and cloud-sql-proxy will pick them all up automatically?

**Comment by enocom** [comment]
Woops. I see I missed this hidden feature. You're right: `INSTANCES` is supported in v1.

We have the equivalent in v2 where you set `CSQL_PROXY_INSTANCE_CONNECTION_NAME_x` as you want (zero indexed) and the Proxy picks them up automatically.  Full info is here: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/cmd/root.go#L240-L265.

**Comment by enocom** [comment]
I'm going to treat this as a docs issue. If there are improvements in how we support environment variables beyond what we already have, feel free to re-open.
