### ISSUE TITLE
Add support for Debian bookworm

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/cloud-sql-proxy#2072]
### Feature Description

Buster LTS ends on June 30, 2024. When that happens, we should update our container images to ship support for bookworm (and drop buster) to match Debian LTS.

https://wiki.debian.org/LTS

### Sample code

```
// sample code here
```

**Comment by JTSG1** [comment]
Buster LTS ended on 30th June, the PR associated (#2118) said Bookworm would be added post that. When is bookworm support expected to happen? It would help address critical vulnerabilities reported with the Bullseye image

**Comment by enocom** [comment]
I think we can get this in our next release (next week).

**Comment by JTSG1** [comment]
That would be incredible

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by enocom** [comment]
This will go out with the release tomorrow. https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/2262
