### ISSUE TITLE
Add FIPS (BoringCrypto) support

### ISSUE THREAD

**Issue by jonacto-google** [GoogleCloudPlatform/cloud-sql-proxy#2108]
### Feature Description

In pursuit of FedRamp authorization, there's a customer need to ensure that all cryptographic modules in use within their GCP environment are FIPS validated. BoringCrypto is one such module that could be used by CloudSQL Auth proxy to meet this requirement.

### Sample code

```
// sample code here
```

**Comment by enocom** [comment]
We're going to hold off on this since boringcrypto doesn't currently support TLS 1.3.
