### ISSUE TITLE
Update storage bucket link in proxy help message

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/cloud-sql-proxy#2145]
### Description

We tried to auto-update the version in the URL in https://github.com/GoogleCloudPlatform/cloud-sql-proxy/commit/1439eeaf8b503b18c46e995e76aa58d7cb0dec38, but that didn't seem to work.

This issue is for tracking that the automation works as expected. 

We should also port this change to AlloyDB Proxy.

**Comment by ttosta-google** [comment]
I've created a draft PR for the next release https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/2147 using the [release-please CLI](https://github.com/googleapis/release-please/blob/main/docs/cli.md) and it shows that `cmd/root.go` file is updated.

However I need to address the issue of release-please incorrectly updating the IP address:

<img width="1480" alt="Screenshot 2024-03-15 at 10 04 59 AM" src="https://github.com/GoogleCloudPlatform/cloud-sql-proxy/assets/91583351/6c071570-93b7-4c34-a33d-1228bb6a2faf">
