### ISSUE TITLE
Version 2.10.0 binaries are all ELF 64-bit LSB executable, x86-64

### ISSUE THREAD

**Issue by Fake51** [GoogleCloudPlatform/cloud-sql-proxy#2153]
### Bug Description

The recent change to config handling seems to have broken your CI/CD. The binaries for ARM, and possibly for Mac/Darwin as well, are broken - they're in ELF format, i.e. generated for AMD64 instead.

### Example code (or command)

```
// paste your code or command here
```

### Steps to reproduce?

```
 wget -O yada https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.10.0/cloud-sql-proxy.darwin.arm64
 --2024-03-20 11:48:36--  https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.10.0/cloud-sql-proxy.darwin.arm64

 Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.9.207, 142.250.147.207, 2a00:1450:4025:c03::cf, ...
 Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.9.207|:443... connected.
 HTTP request sent, awaiting response... 200 OK
 Length: 33083448 (32M) [application/octet-stream]
 Saving to: ‘yada’

 yada                          100%[===============================================>]  31,55M  24,6MB/s    in 1,3s

 2024-03-20 11:48:38 (24,6 MB/s) - ‘yada’ saved [33083448/33083448]

file yada

	yada: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=-swtzDq540l6P9hjIEgE/Ib0kEm_t7DP3y0cJY_c9/FV2GSRwsD8yKQIYf-hAE/K8Xhhh4LnDfH5GGKOGxc, with debug_info, not stripped


```

### Environment

1. OS type and version: really doesn't matter, but linux - ubuntu 22.04.4
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): v2.10.0
3. Proxy invocation command (for example, `./cloud-sql-proxy --port 5432 INSTANCE_CONNECTION_NAME`): any

**Comment by enocom** [comment]
Thanks for the report. We'll get this fixed ASAP.

**Comment by enocom** [comment]
The binaries for v2.10.0 are all fixed now.

We're going to cut a separate patch release just in case the bad binaries have been pulled into automated workflows. It's otherwise identical to v2.10.0.
