### ISSUE TITLE
No Such Host

### ISSUE THREAD

**Issue by tgriff1908** [GoogleCloudPlatform/cloud-sql-proxy#2154]
### Question

The cloud-sql-proxy runs fine as a Windows Service when you have a wired connection but we are experiencing issues when the PC is WIFI only. The service starts, errors with a 'No Such Host' and then the service doesn't restart. Is there a way of handling this? Ideally I need a way of only starting the service when the client has an internet connection.

**Comment by enocom** [comment]
Can you confirm that your machine has proper access to resolve DNS on WiFI? This looks like the Proxy is unable to find a DNS server and errors accordingly.

Also, do you have Proxy logs for this error?

**Comment by enocom** [comment]
Going to assume you sorted out the issue. Feel free to re-open with more info otherwise.
