### ISSUE TITLE
Is there any way to connect to MS SQL using domain credentials? 

### ISSUE THREAD

**Issue by tjlee** [GoogleCloudPlatform/cloud-sql-proxy#2202]
### Question

Is there any way to connect to MS SQL using domain credentials (domian / user / pwd)?

**Comment by jackwotherspoon** [comment]
Yes I believe this should be possible. Have you taken a look at the following https://cloud.google.com/sql/docs/sqlserver/configure-ad#using-proxy-for-ad

**Comment by tjlee** [comment]
Is it possible to do it via JDBC too?

**Comment by tjlee** [comment]
But for me it's still not clear how to pass domain name to JDBC...

**Comment by tjlee** [comment]
I see, thank you

**Comment by jackwotherspoon** [comment]
I've opened an issue on our Java Connector to add guidance on how to use our Java library with AD authentication. 

Going to close this but if you have any additional questions, feel free to re-open 😄 

Thanks so much for the question.
