### ISSUE TITLE
Availability of a Container Image on Google Artifact Registry

### ISSUE THREAD

**Issue by trietsch** [GoogleCloudPlatform/cloud-sql-proxy#2211]
### Question

Since Google Container Registry [is deprecated](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr) in favor of Google Artifact Registry, I was wondering if there are plans to create a container image on one of the `pkg.dev` domains. As these images might fall under the public images that Google Cloud maintains, this could also be relevant for [this question](https://stackoverflow.com/questions/70347732/gcp-artifact-registry-public-google-container-images) I asked a while ago on StackOverflow.
I can't find anything related in issues (open or closed) or in the readme.

**Comment by trietsch** [comment]
Hey @jackwotherspoon, thanks for the quick reply! I did see something like that in the docs regarding the migration, that GCR registries can be hosted by Artifact Registry, but good to know that they are already migrated.

**Comment by hessjcg** [comment]
Closing. The images are stored in Artifact Registry.

**Comment by enocom** [comment]
Let's make that clear in our README here: https://github.com/GoogleCloudPlatform/cloud-sql-proxy?tab=readme-ov-file#container-images
