### ISSUE TITLE
Support configuring proxy with environment variables

### ISSUE THREAD

**Issue by micheas** [GoogleCloudPlatform/cloud-sql-proxy#225]
With instances being a command line argument I cannot use k8s secrets to set the instance and then recycle the same deployment.yaml file between environments, but rather resort to a generator for the k8s config.

An example can be found at:

https://github.com/itkj/docker-cloud-sql-proxy/blob/master/Dockerfile#L10

from itkj/docker-cloud-sql-proxy on docker hub.

**Comment by enocom** [comment]
We're working on some major structural improvements to the proxy. Once those are complete, we'll come back to address this issue.

**Comment by enocom** [comment]
The new v2 proxy uses [cobra](https://github.com/spf13/cobra) and makes it easy to integrate with [viper](https://github.com/spf13/viper). Now that the v2 proxy is out, I have this in my backlog.

**Comment by enocom** [comment]
This work will unblock https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1045.

**Comment by enocom** [comment]
I think we should make the list of instance connection names zero indexed and also define an INSTANCE_CONNECTION_NAME variable for the first instance, for the cases when someone is connecting to only a single instance:

```
CLOUD_SQL_PROXY_INSTANCE_CONNECTION_NAME=proj:reg:myinst
CLOUD_SQL_PROXY_INSTANCE_0=proj:reg:myinst
CLOUD_SQL_PROXY_INSTANCE_1=proj:reg:myotherinst
```

**Comment by enocom** [comment]
Also, to configure individual instances, we'll continue to use query params:

```
CLOUD_SQL_AUTO_IAM_AUTHN=true
CLOUD_SQL_PROXY_INSTANCE_0=proj:reg:myinst?auto-iam-authn=false
```
