### ISSUE TITLE
Unix socket: add switch to disable adding the instance name to path

### ISSUE THREAD

**Issue by eldad** [GoogleCloudPlatform/cloud-sql-proxy#2302]
### Feature Description

When creating a unix socket (`-u`), the name of the instance is concatenated to the path given by `-u`. This can cause an issue even if `-u` is very short: when using a long instance name, creating a UNIX socket can fail due to the length restriction.
(See also https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/970)

This can be avoided if `cloud-sql-proxy` would allow the user to disable adding the instance name as an extra directory, which is done here:
https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/c6830422a5b098871836e509e8c06c7972f49625/internal/proxy/proxy.go#L892

I was able to workaround my local issues by building a custom version with `address = dir` at that line.
It would be great if there would be a switch to control this.

If this is acceptable to you, I'll be happy to contribute a PR to implement this.

### Additional Details

Related issue: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/970

With this simple change I can work with very long instance names:
https://github.com/eldad/cloud-sql-proxy/commit/950bb2a8e0502bd73dc0963fb1c6ed9e9eb78281
(obviously this behavior would need to be feature-flag controlled)

**Comment by hessjcg** [comment]
Hi, you are going to want to use the `unix-socket-path` parameter. This allows you to override the default socket path with your own, absolute path to the socket. 

From the docs:

  When necessary, you may specify the full path to a Unix socket. Set the
  unix-socket-path query parameter to the absolute path of the Unix socket for
  the database instance. The parent directory of the unix-socket-path must
  exist when the Proxy starts or else socket creation will fail. For Postgres
  instances, the Proxy will ensure that the last path element is
  '.s.PGSQL.5432' appending it if necessary. For example,

```
      ./cloud-sql-proxy \
        'my-project:us-central1:my-db-server?unix-socket-path=/path/to/socket'
```

**Comment by eldad** [comment]
Thanks, I was not aware of this option!
It would be great if it would be at mentioned in the `--help` text.

**Comment by jackwotherspoon** [comment]
> It would be great if it would be at mentioned in the `--help` text

@eldad It is mentioned in the `--help` text, albeit somewhat hidden in the text.

https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/c6830422a5b098871836e509e8c06c7972f49625/cmd/root.go#L160-L169

**Comment by eldad** [comment]
Hidden in plain sight :smile: My bad, I didn't even notice the whole text before the command line switches. Thanks again!
