### ISSUE TITLE
IAM username then db name is truncated in version 2.13.0+linux.amd64 

### ISSUE THREAD

**Issue by ss153g** [GoogleCloudPlatform/cloud-sql-proxy#2304]
### Bug Description

When attempting to connect to Cloud SQL Proxy using IAM username, the db name is truncated.
`SQLALCHEMY_DATABASE_URI = f'postgresql+pg8000://{db_pg_iam_user}:@/cloudsql/{db_pg_conn}/{db_pg_name}'`
`db_pg_iam_user` is the IAM user
`db_pg_conn` is the db instance name
`db_pg_name` is the database name

### Example code (or command)

```
// paste your code or command here
```
`SQLALCHEMY_DATABASE_URI = f'postgresql+pg8000://{db_pg_iam_user}:@/cloudsql/{db_pg_conn}/{db_pg_name}'`
`db_pg_iam_user` is the IAM user
`db_pg_conn` is the db instance name
`db_pg_name` is the database name

### Stacktrace

```bash
sqlalchemy.exc.ProgrammingError: (pg8000.dbapi.ProgrammingError) {'S': 'FATAL', 'V': 'FATAL', 'C': '3D000', 'M': 'database "cloudsql/GOOGLE_PROJECT_NAME:REGION:postgresql-16-sa" does not exist', 'F': 'postinit.c', 'L': '1039', 'R': 'InitPostgres'}
(Background on this error at: https://sqlalche.me/e/20/f405)
```

`cloudsql/GOOGLE_PROJECT_NAME:REGION:postgresql-16-sa` is the truncated value of the actual database. It appears that even I add a db name that's short, some characters were STILL truncated, thus producing the same error.

### Steps to reproduce?

1. Setup PostgreSQL Instance and allow IAM permissions
2. Use Flask==3.0.0 & SQLAlchemy==2.0.23
3. Set the `SQLALCHEMY_DATABASE_URI` like:  `f'postgresql+pg8000://{db_pg_iam_user}:@/cloudsql/{db_pg_conn}/{db_pg_name}'` where
`db_pg_iam_user` is the IAM user
`db_pg_conn` is the db instance name
`db_pg_name` is the database name
5. Install cloud-sql-proxy version 2.13.0+linux.amd64
6. Try connecting using the IAM via Linux distro and the issue appears. 
7. Connecting via macOS distribution does not create issues. Or connecting via Linux distro using username/password.
...

### Environment

1. OS type and version: `Debian 12`
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): `version 2.13.0+linux.amd64`
3. Proxy invocation command (for example, `./cloud-sql-proxy --port 5432 INSTANCE_CONNECTION_NAME`): `./cloud-sql-proxy GOOGLEPROJECT:REGION:INSTANCE --credentials-file CREDFILE.json --port 5432 --debug-logs --structured-logs --auto-iam-authn --private-ip --run-connection-test`

### Additional Details

1. Connecting via macOS distribution does not create issues. Or connecting via Linux distro using username/password.
2. It appears that even I add a db name that's short, some characters were STILL truncated when using IAM via Linux distro, thus producing the same error.

**Comment by jackwotherspoon** [comment]
@ss153g Thanks for raising an issue on the Cloud SQL Proxy 😄 

It seems like there is a bit of confusion here, I will try and help you get it all sorted.

There are two different ways (modes) to configure and start the Cloud SQL Proxy:

1. TCP connection: Listens on a local address and port for connections. (default mode, `--port` flag)
2. Unix domain socket connection: Listens on a local unix socket for connections. (`--unix-socket`)

It seems like you are trying to intermingle the two which is causing your error. 

You are starting the Proxy up with `--port 5432` which is telling the Proxy to listen on `127.0.0.1:5432` for TCP connections. 

Yet in your SQLAlchemy URI you are using the `/cloudsql/<INSTANCE_CONNECTION_NAME>` which is expecting the Proxy to be using a Unix socket connection.

This mismatch is the cause of your error. Updating your SQLAlchemy URI to the following should fix your setup:

```python
SQLALCHEMY_DATABASE_URI = f'postgresql+pg8000://{db_pg_iam_user}:@127.0.0.1:5432/{db_pg_name}'
```

> [!NOTE] 
>
> It is also worth pointing out since you are using `pg8000` that there is the [Cloud SQL Python Connector](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector) which provides all the same benefits of the Cloud SQL Proxy but as a native Python package that can easily be pip installed)

**Comment by ss153g** [comment]
Thank you sooo much for the correction. That indeed did work as expected.

So, I am this connection only to connect my local environment with the database via IAP tunneling to a VM that has Cloud SQL Proxy running. 

Is there a way to use Cloud SQL Python Connector to connect from my local environment to the database?
```
from google.cloud.sql.connector import Connector

connector = Connector(
    enable_iam_auth=True,
    ip_type="private",
)
class Config():
    def getconn(self):
        conn = connector.connect(
            "INSTANCE_CONNECTION_NAME",
            "pg8000",
            db="DB_NAME",
            user="IAM_USER_NAME",
        )
        return conn

    SQLALCHEMY_DATABASE_URI = "postgresql+pg8000://"
    SQLALCHEMY_ENGINE_OPTIONS = {
         "creator": getconn
    }
```

I'm using Cloud SQL Python Connector for my app is running in GCP.

**Comment by jackwotherspoon** [comment]
@ss153g Glad you got your setup working!

> So, I am using this connection only to connect my local environment with the database via IAP tunneling to a VM that has Cloud SQL Proxy running.

Ah I see, then yes you have a good approach setup! 😄 👍
