### ISSUE TITLE
More cloudsql connection

### ISSUE THREAD

**Issue by wagnerww** [GoogleCloudPlatform/cloud-sql-proxy#2319]
### Question

I use cloudsql as a sidecar and I have 2 connections in the following model:
- -instances=<INSTANCE_NAME>=tcp:127.0.0.1:5432,<INSTANCE_NAME>=tcp:127.0.0.2:5432

How do I run this in version 2?

**Comment by jackwotherspoon** [comment]
Hi @wagnerww thanks for the great question! 😄 

What you are looking for is instance level configuration, this can be done with query strings.

https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/bf75246386a5c4fe5bc46274f8565b295b280a1c/cmd/root.go#L143-L160

The v2 command for you would be:

```
./cloud-sql-proxy <INSTANCE_NAME>  <INSTANCE_NAME2>?address=127.0.0.2&port=5432' 
```

> [!NOTE]
>
> Your could optionally add the `?address=127.0.0.1&port=5432` query string to the first instance connection name, 
> however I omitted it for simplicity as the first configured instance will default to `127.0.0.1:5432`.

To see a full list of supported features you can always run `./cloud-sql-proxy --help`

Migration guide with more details can be found here: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/migration-guide.md

**Comment by wagnerww** [comment]
Great! Thank you!
How to use with sidecar:

```
image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.0
command:
- /cloud-sql-proxy
- <INSTANCE_NAME>
- <INSTANCE_NAME2>?address=127.0.0.2&port=5432
```
