### ISSUE TITLE
Add `--role` flag to allow **SQL** role impersonate

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/cloud-sql-proxy#2320]
### Feature Description

For example, consider the `terry.crews@acme.invalid` IAM user in a hypothetical Cloud SQL instance:

```
acme> SELECT CURRENT_USER;
+--------------------------+
| current_user             |
|--------------------------|
| terry.crews@acme.invalid |
+--------------------------+
SELECT 1
Time: 0.032s

acme> \du terry*
+--------------------------+----------+------------+---------------+-------------+-------------+--------------+---------------+--------------------------------+----------------+
| rolname                  | rolsuper | rolinherit | rolcreaterole | rolcreatedb | rolcanlogin | rolconnlimit | rolvaliduntil | memberof                       | rolreplication |
|--------------------------+----------+------------+---------------+-------------+-------------+--------------+---------------+--------------------------------+----------------|
| terry.crews@acme.invalid | False    | True       | False         | False       | True        | -1           | <null>        | ['cloudsqliamuser', 'acme_ro'] | False          |
+--------------------------+----------+------------+---------------+-------------+-------------+--------------+---------------+--------------------------------+----------------+
SELECT 1
Time: 0.036s
```

For the **connection**, I want to use the `terry.crews@acme.invalid` IAM role, but for my actual SQL role, I want to use the `acme_ro` role. E.g.

```
acme> SET ROLE acme_ro;
SET
Time: 0.028s

acme> SELECT CURRENT_USER;
+--------------+
| current_user |
|--------------|
| acme_ro      |
+--------------+
SELECT 1
Time: 0.038s
```

### Alternatives Considered

You may also consider providing an `--on-connect` flag so a user could just specify:

```
./cloud-sql-proxy \
  prod-acme-zebra3:us-central1:acme-postgres \
  --auto-iam-authn \
  --private-ip \
  --port 15079 \
  --on-connect 'SET ROLE acme_ro'
```

**Comment by jackwotherspoon** [comment]
Hi @dhermes thanks for raising a feature request on the Cloud SQL Proxy! 😄 

Do you mind providing a bit more detail on the use-case for this feature and the problem it is solving?Just curious what is the benefit of impersonating the SQL role that the IAM user is already a member of?

Is the use-case just so that you don't have to run `SET ROLE acme_ro;` from your own client for each connection?

**Comment by dhermes** [comment]
@jackwotherspoon For many commands (DML), it's likely not critical. But for DDL, it can be very critical. Depending on how the DDL SQL is formed, it can impact ownership. For example:

```
acme> CREATE TABLE zebra.foo1 ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), v INTEGER NOT NULL );
CREATE TABLE
Time: 0.011s

acme> SET ROLE acme_admin;
SET
Time: 0.003s

acme> CREATE TABLE zebra.foo2 ( id UUID PRIMARY KEY DEFAULT gen_random_uuid(), v INTEGER NOT NULL );
CREATE TABLE
Time: 0.017s

acme> \dt zebra.foo*
+--------+------+-------+--------------------------+
| Schema | Name | Type  | Owner                    |
|--------+------+-------+--------------------------|
| zebra  | foo1 | table | terry.crews@acme.invalid |
| zebra  | foo2 | table | acme_admin               |
+--------+------+-------+--------------------------+
SELECT 2
Time: 0.011s
```

**Comment by dhermes** [comment]
@jackwotherspoon Thanks for the info! I was assuming that the proxy was sending a [Start-up][1] packet to PostgreSQL and actually doing things (at the binary level) to indicate the connection.

I realize now that given the use of mTLS, the user can be determined by Cloud SQL (the server) without need for looking inside the Start-up packet.

Cheers!

[1]: https://www.postgresql.org/docs/17/protocol-flow.html#PROTOCOL-FLOW-START-UP
