### ISSUE TITLE
Loadbalancing of read-replicas using cloudsql proxy

### ISSUE THREAD

**Issue by harshv1995** [GoogleCloudPlatform/cloud-sql-proxy#2355]
### Question

Here we have two read replicas, and we are trying to create loadbalancing between the two replicas.

### Code

```Go
this is my container spec

      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.2
        args:
        - "--structured-logs"
        - "--private-ip"
        - "--address=0.0.0.0"
        - "--port=5432"
        - "--prometheus"
        - "--http-address=0.0.0.0"
        - "--http-port=10011"
        - "instance-0-connection-name"
        - "instance-1-connetion-name"
```
what actually happens is instance-0-connection-name starts on 5432 and instance-1-connetion-name" on 5433, does cloudsql has any argument which may do some loadbalancing on top of the instance-0 and instance-1 as both of them are same read replicas
```


### Additional Details

_No response_

**Comment by jackwotherspoon** [comment]
Hi @harshv1995, thanks for the great question! 😄 

Unfortunately, today Cloud SQL does not support load balancing between read replicas. You can find this mentioned in the [official docs](https://cloud.google.com/sql/docs/mysql/replication#rr-info) under "Load balancing".

However, you can setup your own external load balancing, there is a good [Google Cloud Forum post](https://www.googlecloudcommunity.com/gc/Databases/Load-Balancer-for-Postgres/m-p/647537/highlight/true#M1761) which goes over several approaches of using an external load balancer such as HAProxy.
