### ISSUE TITLE
More actionable errors

### ISSUE THREAD

**Issue by kurtisvg** [GoogleCloudPlatform/cloud-sql-proxy#278]
Provide suggested actions to address errors

* "Connect time out" -> Validate networking path
* "Not Authorized" -> Verify instance name or IAM permissions (instance doesn't exist or no permission to access).
* "Not configured" -> Enable Cloud SQL Admin API

**Comment by enocom** [comment]
This issue will be addressed as part of the Cloud SQL Proxy v2 work described in #872.

**Comment by enocom** [comment]
This is fixed in the recent public preview of v2: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/releases/tag/v2.0.0.preview.0.
