### ISSUE TITLE
Allow raw JSON to be passed into GOOGLE_APPLICATION_CREDENTIALS env variable

### ISSUE THREAD

**Issue by mholyak** [GoogleCloudPlatform/cloud-sql-proxy#323]
... or into new env variable.

Usecase is using service in bitbucket pipelines:

![image](https://user-images.githubusercontent.com/5064823/67696575-cc148280-f9af-11e9-8586-03a748f5035d.png)

**Comment by kurtisvg** [comment]
While this isn't the exact useless you described, you can use the `-token` flag to pass in credentials to the proxy when it starts (which could rely on a env var).

**Comment by Carrotman42** [comment]
Is there a way to store a file to disk using the bitbucket configuration?
That's seems like a pretty basic feature it should support (never used it,
haven't checked, just a guess). If you can manage that, then the Proxy
doesn't need anything extra from what already exists: store that file to
disk somewhere, and then point to it using the existing flags/env variables
for authentication.

**Comment by Carrotman42** [comment]
I don't think -token works for this: the json credentials include a private
key for obtaining oauth tokens (via Google auth APIs), but -token should
take the oauth token itself (implying something else has to call the Google
APIs).

**Comment by mholyak** [comment]
> Is there a way to store a file to disk using the bitbucket configuration?

Sure, and I'm using it now to run cloud-proxy in background

![image](https://user-images.githubusercontent.com/5064823/67698336-d7b57880-f9b2-11e9-8e7f-8c3911403dc3.png)

But, if I want to have it as stand-alone service _(similar to docker-compose items)_ I need to define it in special separate section and only env variables are available there...

**Comment by gregmsanderson** [comment]
+1 for this, seems like a great idea to be able to pass the json content. Since many faas/paas seem to support using secrets in key => value form. So then the content of the json could be stored once, as a secret, and then that file then never needs to be kept in a file system.

**Comment by y0ssar1an** [comment]
+1 for this. Requiring that the file be present on the filesystem makes `cloud_sql_proxy` difficult to use with `terraform`. [This code search of GitHub](https://github.com/search?q=filename%3A.tf+cloud_sql_proxy&type=Code) shows that the only way anybody has figured out how to deploy `cloud_sql_proxy` with `terraform` is to use k8s volume mounts.

I think the scarcity of `terraform`+`cloud_sql_proxy` usage on GitHub points to a serious usability problem. It is, of course, up to you whether you want to support `terraform`. If you do, allowing us to set the entire service account key as an env var would make `cloud_sql_proxy` _much_ easier to use. Thanks for keeping this issue open and considering this feature.

**Comment by enocom** [comment]
We don’t control GOOGLE_APPLICATION_CREDENTIALS and so can’t change how it works. However, there is a [CredentialsFromJSON](https://pkg.go.dev/golang.org/x/oauth2@v0.0.0-20220909003341-f21342109be1/google#CredentialsFromJSON) method that we could in theory expose as a CLI flag. That said I don’t understand the use case here and why using a credential file isn’t a reasonable option.

**Comment by ryboe** [comment]
The use case is: it's easier to pass the credentials into a container as an env var instead of mounting them as a volume. Look at [all the templating hoops I had to jump through to deploy Cloud SQL Proxy with Terraform](https://medium.com/p/e184b08eca64#7aa8). Also, lots of container environments are restricted (e.g. CI/CD) and don't let you mount volumes. But just about every container environment lets you set env vars.

**Comment by enocom** [comment]
This is on main now and will be available in the next preview release of v2 (preview 2).
