### ISSUE TITLE
sql proxy should be distributed via chocolateley on Windows

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-sql-proxy#352]
Currently sql proxy is distributed as raw EXE file, which might pose security risk for developers trying to install it in their environments. Organizations might block downloading zip files and raw exe/dll files.
 
On Windows, chocolately is a standard way of distributing packages of tools, similar to brew on MAC.
https://chocolatey.org/
It provides package version management, history, download statistics and more.

We should create choco feed for sql proxy and distribute all the releases via choco on Windows.

**Comment by kurtisvg** [comment]
Quickstart for packaging: https://chocolatey.org/docs/CreatePackagesQuickStart

**Comment by enocom** [comment]
Given the limited interest here, I'm going to close this request. If we had more time and help, ideally we'd distribute the proxy in Chocolatey, Homebrew, dpkg, etc. But for now the big targets for us are gcloud, and a separate binary distribution.
