### ISSUE TITLE
Add example systemd/upstart configs for running the proxy as a service

### ISSUE THREAD

**Issue by vadimberezniker** [GoogleCloudPlatform/cloud-sql-proxy#4]

**Comment by israelfaria** [comment]
Hi, after some fiddling into how to do this properly on Ubuntu 15.10 images I was able to pull [this solution](https://gist.github.com/israelfaria/d47094551b1afe6c7f125cb749882f9e). It could be easier but it's good enough for me and needs no startup scripts.

**Comment by emilv** [comment]
@israelfaria You don't need the `daemon` package at all. Systemd already provides the same functionality. Here is my unit file:

```
[Install]
WantedBy=multi-user.target

[Unit]
Description=Google Cloud Compute Engine SQL Proxy
Requires=networking.service
After=networking.service

[Service]
Type=simple
WorkingDirectory=/run/cloudsql
ExecStart=/usr/local/bin/cloud_sql_proxy -dir=/run/cloudsql -instances=...
Restart=always
StandardOutput=journal
User=root
```

**Comment by idoshamun** [comment]
@emilv I had to change the `WorkingDirectory` to `/usr/local/bin/` to make it work

**Comment by oussamahammami** [comment]
Hi all,

Here is my working systemd service tested in `Centos 7` :

**`/usr/lib/systemd/system/cloud_sql_proxy.service`**

```ini
[Unit]
Description=GCP CloudSQL Proxy
After=network.target

[Service]
User=asterisk
Group=asterisk
WorkingDirectory=/usr/bin
Type=forking
RemainAfterExit=yes
ExecStart=/bin/sh -c '/usr/bin/nohup /usr/local/cloud_sql_proxy -instances=${INSTANCE_CONNECTION_NAME} -credential_file=${CREDENTIAL_FILE} &'
StandardOutput=journal
KillMode=process

[Install]
WantedBy=multi-user.target
```

**/`usr/lib/systemd/system/cloud_sql_proxy.service.d/settings.conf`**

```ini
[Service]
Environment=INSTANCE_CONNECTION_NAME=[YOUR CONNECTION NAME]
Environment=CREDENTIAL_FILE=[PATH TO YOUR CREDENTIAL FILE]
```

BR
/Ouss

**Comment by gdsotirov** [comment]
This is what works for me on CentOS 8:

```ini
[Unit]
Description=Cloud SQL Proxy service
Wants=network-online.target
After=network-online.target

[Service]
WorkingDirectory=/usr/bin
ExecStart=/usr/bin/cloud_sql_proxy -instances=...=tcp:3306
Restart=always
Type=simple
StandardError=syslog
StandardOutput=journal
KillMode=process

[Install]
WantedBy=multi-user.target
```

It would be good if a service unit is provided upstream, but apparently this has not happened in the past almost 5 years.

**Comment by ezarowny** [comment]
I recently had to fall back to using the root user instead of a system user and I cannot figure out why for the life of me. Proxy was reporting:

```
2021/03/05 19:31:43 GcloudConfig: error reading config: exit status 1; stderr was:
WARNING: Could not setup log file in /bin/.config/gcloud/logs, (Error: Could not create directory [/bin/.config/gcloud/logs/2021.03.05]: Permission denied.

Please verify that you have permissions to write to the parent directory.)
ERROR: (gcloud.config.config-helper) Failed to create the default configuration. Ensure your have the correct permissions on: [/bin/.config/gcloud/configurations].
  Could not create directory [/bin/.config/gcloud/configurations]: Permission denied.

Please verify that you have permissions to write to the parent directory.
2021/03/05 19:31:44 GcloudConfig: error reading config: exit status 1; stderr was:
WARNING: Could not setup log file in /bin/.config/gcloud/logs, (Error: Could not create directory [/bin/.config/gcloud/logs/2021.03.05]: Permission denied.

Please verify that you have permissions to write to the parent directory.)
ERROR: (gcloud.config.config-helper) Failed to create the default configuration. Ensure your have the correct permissions on: [/bin/.config/gcloud/configurations].
  Could not create directory [/bin/.config/gcloud/configurations]: Permission denied.
```

My systemd script is very similar to everyone else's.

**Comment by enocom** [comment]
Not so long ago, a [change](https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/719) added support for `Type=notify`.

**Comment by jawnsy** [comment]
Support for macOS with an example launchd service plist would be nice as well, I'd be happy to contribute one but I'll likely need to sort out Google's CLA with our legal team before doing so

**Comment by jawnsy** [comment]
Here's an example plist that I'm using with v2 of the proxy:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>com.google.CloudSQLProxy</string>
    <key>Program</key>
    <string>/Users/jawnsy/.local/bin/cloud-sql-proxy</string>
    <key>ProgramArguments</key>
    <array>
      <string>cloud-sql-proxy</string>
      <string>--auto-iam-authn</string>
      <string>--private-ip</string>
      <string>--max-connections</string>
      <string>50</string>
      <string>--unix-socket</string>
      <string>/Users/jawnsy/.local/run/postgresql</string>
      <string>PROJECT_ID:REGION:INSTANCE_ID</string>
    </array>
    <key>StandardOutPath</key>
    <string>/tmp/cloud-sql-proxy.stdout.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/cloud-sql-proxy.stderr.log</string>
    <key>RunAtLoad</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>/tmp</string>
    <key>Data</key>
    <integer>104857600</integer>
  </dict>
</plist>
```

**Comment by viraj8pop** [comment]
You have all examples above. if you need integrated with terraform and startup script. Here it is.

metadata_startup_script = <<SCRIPT
        sudo apt -y update && sudo apt -y upgrade
        sudo apt -y install gnupg2 wget vim
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt -y update
        sudo apt -y install postgresql-14
        sudo apt update && sudo apt upgrade
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /root/cloud_sql_proxy
        chmod 700 /root/cloud_sql_proxy
        shopt -s xpg_echo
        echo "[Unit]\nDescription=cloudproxy sql service\nAfter=network.target auditd.service\n[Service]\nUser=root\nWorkingDirectory=/root\nExecStart=/bin/bash -c 'cd /root/ && ./cloud_sql_proxy -instances=${var.project_name}:${var.region_name}:${var.cloud_sql_db_name}=tcp:0.0.0.0:3306 -ip_address_types=PRIVATE'\nRestart=on-failure\n\n[Install]\nWantedBy=multi-user.target" > /etc/systemd/system/sqlproxy.service
        systemctl daemon-reload
        sleep 10
        systemctl start sqlproxy.service
        systemctl enable sqlproxy.service
        SCRIPT

**Comment by enocom** [comment]
There are some good suggestions in the thread here that seem to satisfy the initial request.
