### ISSUE TITLE
cloud-sql-proxy v2

### ISSUE THREAD

**Issue by kurtisvg** [GoogleCloudPlatform/cloud-sql-proxy#872]
## Feature Description
This issue is tracking work on the next major version bump for the Cloud SQL proxy. V1 of this library has been around for over 5 years, and along the way both this library and the Go language have grown a lot. We think some of the improvements/changes we'd most like to see in the proxy may be impossible or severely more difficult without a major version bump. 

### High Priority
- Separate dial functionality - https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/870
- Instance level metrics/tracing - https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/169
- Explicitly defined public API
- Actionable Errors - https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/278

### Medium Priority

- Default to listening on TCP port
- Per instance configuration for things like `ipTypes` and `iam_login`
- Find a replacement fuse library, or remove fuse support for MacOS - https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/382

### Low Priority

- Straightforward logging behavior to std out by default
- POSIX compliant flags

Anything we missed? Please feel free to chime in or provide feedback on anything you'd like to see (or not see).

**Comment by enocom** [comment]
We have a preview release here: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/releases/tag/v2.0.0.preview.0.

We'll continue to make minor changes and solicit feedback before making this GA.
