### ISSUE TITLE
Liveness probe did not restart container on bad connection

### ISSUE THREAD

**Issue by Firehed** [GoogleCloudPlatform/cloud-sql-proxy#980]
## Bug Description

We experienced downtime yesterday as a result of sqlproxy failing to renew the certificates (presumably fixed in #883 but we haven't updated to 1.26 yet). The instance is run inside of GKE using the exact healthchecks given in [this example](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/e90e3fa2ab0bb1cf8a174c907c595e62a7d1986b/examples/k8s-health-check/README.md). Our logs were saturated with the following error message:

```
Reading data from **instance name** had error: remote error: tls: bad certificate
```

The issue was resolved by one of our engineers manually restarting the pod, which (I assume) caused the new certificate generation process to work.

As far as I can tell, at no point did any of the k8s health checks fail, as the pod never got restarted.

I would expect that a bad or expired certificate would cause, at minimum, the liveness probe to fail so that the pod would be restarted (readiness should likely fail too, but in any case the proxy has entered an unusable state).

## Example code (or command)

Health checks used exactly as shown here: https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/e90e3fa2ab0bb1cf8a174c907c595e62a7d1986b/examples/k8s-health-check/proxy_with_http_health_check.yaml#L77-L111

## How to reproduce

Unsure, we are assuming it was some sort of upstream API issue.

## Environment

GKE: `Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-gke.1200", GitCommit:"ee714a7b695ca42b9bd0c8fe2c0159024cdcba5e", GitTreeState:"clean", BuildDate:"2021-08-03T09:21:57Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}`

Proxy: Cloud SQL Auth proxy: 1.25.0+container

**Comment by Firehed** [comment]
Hm, interesting. It looks like that change should have been 1.25.0 which we're currently running (well, we're now upgrading to 1.26.0).

I've got a two-second window in our logs (2021-10-14 19:03:37-39) with dial TCP connection refused entries, immediately followed by the bad certificate errors. Those bad cert errors continued until someone manually restarted the proxy deployment (most recent log entry). The new pods spun up by k8s resolved the issue.

Note logs are newest on top:

```
2021-10-15T03:38:39.000Z,cloudsql-sqlproxy,Received TERM signal. Waiting up to 0s before terminating.
# next line repeated continuously until SIGTERM
2021-10-15T02:04:39.000Z,cloudsql-sqlproxy,Reading data from **** had error: remote error: tls: bad certificate
# next line repeated ~ 40 times over two seconds
2021-10-15T02:04:37.000Z,cloudsql-sqlproxy,"couldn't connect to ""****"": dial tcp ****:3307: connect: connection refused"
2021-10-15T02:04:37.000Z,cloudsql-sqlproxy,Reading data from **** had error: read tcp 10.84.3.21:40468->****:3307: read: connection reset by peer
# next line repeated about once a day at the same time
2021-10-14T14:07:15.000Z,cloudsql-sqlproxy,Scheduling refresh of ephemeral certificate in 23h54m59.735901417s
```

Beyond that, I have no other logs available. Further, I see no metrics indicating the pod was restarted by k8s.

It looks like the refresh scheduling occurred daily at about the same time since the pod started. Right about 12 hours after the "scheduling refresh" message, two seconds of "connection refused" followed by continual "bad certificate".

I can't imagine this is relevant, but I'll mention it anyway: the failed proxy wasn't deployed using the sidecar pattern, but instead had a standalone Deployment and Service. AFAICT, none of our other proxy instances (both sidecars and standalone deployments) for other databases were affected. I did check the cloud sql dashboard, logs, etc for the db in question and didn't see any maintenance, or really any messages beyond corresponding connection refusals.

Any other info I can provide to help? Happy to pull what I can for you.

**Comment by enocom** [comment]
Just to confirm, how are you starting the proxy (what flags etc)?
